### ISSUE TITLE
what serializations of rdf are expected for import codelist in skos format

### ISSUE THREAD

**Issue by pvgenuchten** [halestudio/hale#1020]
We tried to import
https://raw.githubusercontent.com/rapw3k/glosis/master/glosis_procedure.ttl
but hale studio (v4.0.0) was not able to detect the serialisation

I converted the ttl to rdf/xml, and then the codelist was loaded correctly

**Comment by thorsten-reitz** [comment]
I think it expects an RDF/XML encoding. of SKOS.

**Comment by pvgenuchten** [comment]
thanks Thorsten, indeed the rdf/xml serialisation works fine, maybe of interest to add to the interface? option `Skos (rdf/xml)`
