### ISSUE TITLE
[Feature]: Add paramter "resolvedepth" in UI when downloading data via WFS

### ISSUE THREAD

**Issue by annat2022** [halestudio/hale#1085]
**Is your feature request related to a problem? Please describe.**
If you download source data via WFS and you want to resolve all links in the data you can use the parameter `resolvedepth`. Currently you have to add this parameter manually to your GetFeatureRequest. 
It would be nice to have a toggle in the UI to be able to add this parameter automatically.

**Describe the solution you'd like**
If you want to download source data via WFS you can add your GetCapabilities link. In the UI you will once navigate to the _Additional configuration options_ dialogue. A toggle to _resolve links_ could be added here 

![grafik](https://github.com/halestudio/hale/assets/116007248/0cf1e4a8-b54c-4b5f-8fd2-315d320bb114)

**Comment by Kate-Lyndegaard** [comment]
Currently investigating this issue.

**Comment by emanuelaepure10** [comment]
The features related to "resolvedepth" have been added
![image](https://github.com/halestudio/hale/assets/67077116/b331f736-7cbb-447e-b4af-781491b5d150)
