### ISSUE TITLE
[BUG]: Changes in the INSPIRE schemas are not visible

### ISSUE THREAD

**Issue by fabiovinci** [halestudio/hale#1098]
**Describe the bug**
After the update of an INSPIRE schema (e.g. change of the data type of an attribute), hale does not show the change.

Example:
In the application schema "[Common Utility Network Elements](https://inspire.ec.europa.eu/schemas/us-net-common/4.0/UtilityNetworksCommon.xsd)" the datatype of the "authorityRole" attribute was updated (see the [related issue](https://github.com/INSPIRE-MIF/application-schemas/issues/83)):
the current definition:

```xml
<element maxOccurs="unbounded" name="authorityRole" type="gml:ReferenceType">
```
was replaced by:

```xml
<element maxOccurs="unbounded" name="authorityRole">
           <complexType>
              <sequence>
                <element ref="base2:RelatedParty"/>
              </sequence>
           </complexType>
    </element>
```
The updated schema is available at: https://raw.githubusercontent.com/INSPIRE-MIF/application-schemas/689152720f45951131b0866a017e0cf97548472d/schemas/us-net-common/4.0/UtilityNetworksCommon.xsd

When the updated schema is imported in hale, the old encoding is shown in the schema explorer (see screenshot below).

**Test done**
The following tests were performed, but the error persists:
1. hale version 5.0.1. was uninstalled and reinstalled
2. hale version 3.5 was installed
3. the workspace folder HALE in %APPDATA%\wetransform was deleted
4. the "Clear Cache" function was used
5. removing the "eu.esdihumboldt.util.resource.schemas.inspire_xxxx.xx.xx.jar" file from the plugins folder

**Screenshots**
![image](https://github.com/halestudio/hale/assets/22212406/f11d6f69-d0c4-4609-a992-d111e543d9b7)

**Additional context**
It was tested a local copy of the xsd (attached here [UtilityNetworksCommon_mod.zip](https://github.com/halestudio/hale/files/13988988/UtilityNetworksCommon_mod.zip)) in which the attribute "authorityRole" was renamed and duplicated using an alternative encoding for the datatype.

![image](https://github.com/halestudio/hale/assets/22212406/189d27fd-ea61-431e-a2e2-857605919d7c)

The import of this xsd generates a very strange behaviour in hale since the two renamed attributes are correctly shown with the right datatype, but also the attribute "authorityRole" (not physically present in the xsd) is shown with the old encoding.

![image](https://github.com/halestudio/hale/assets/22212406/16ac10f5-77f8-4d5e-bf97-7952b499e41e)

The same error appears also for other schemas.

**Comment by JohannaOtt** [comment]
@fabiovinci This is expected - see #960 . There are also links to workarounds available.
In order to have the changes available in the presets, an update of the bundled resources and a release is needed for that.

**Comment by fabiovinci** [comment]
Hi @JohannaOtt ,
I'm loading schemas "From file" and "From URL" , so I'm not using the INSPIRE preset schemas.
So, I expect Hale to load exactly the schema I'm loading.

**Comment by JohannaOtt** [comment]
@fabiovinci This does not matter as the presets are used as soon as the same URLs are used - see [this comment](https://github.com/halestudio/hale/issues/960#issuecomment-1090176855)

> The mechanism with the offline resources in hale works in the way that for a given host name, hale first tries to find the resources (e.g. XML Schema) in the offline resource bundles and if it does not find them it will use the online resource.

**Comment by fabiovinci** [comment]
Dear all,

I confirm that the issue is no longer present in the latest version of halestudio.
