### ISSUE TITLE
Update splash screen and icons

### ISSUE THREAD

**Issue by stempler** [halestudio/hale#110]
Splash screen and icons (and maybe about) should be updated to the new halestudio CI.

**Comment by thorsten-reitz** [comment]
True. Should I provide the appropriate designs? Any requirements?

**Comment by thorsten-reitz** [comment]
Which resolution should the splash screen have?

**Comment by stempler** [comment]
Here a list of all resources:
- Window Images (GIF or PNG; 16x16, 32x32, 48x48, 64x64, 128x128, 256x256)
- About image (GIF or PNG; 250x330) - currently shows hale, wetransform and dhp logos
- Splash image (BMP; 480x300) - should have some space at the bottom with nothing in the foreground, as the version information will be put on top of it dynamically
- Launcher icons
    - Windows: Either 7 BMP images (16x16 8bit, 16x16 32bit, 32x32 8bit, 32x32 32bit, 48x48 8bit, 48x48 32bit, 256x256 32bit) or a single ICO file containing all 7 images
    - Mac OS X: A single ICNS file
    - Linux: A single XPM file

**Comment by thorsten-reitz** [comment]
Here are the resources:
![halestudiosplash30](https://cloud.githubusercontent.com/assets/3470356/17642450/2ad13308-6148-11e6-9936-e889910b5254.png)
[haleStudioIcons3.0.zip](https://github.com/halestudio/hale/files/416483/haleStudioIcons3.0.zip)
![halestudioabout30](https://cloud.githubusercontent.com/assets/3470356/17642451/2ad5e2a4-6148-11e6-851e-0498147a9c10.png)
