### ISSUE TITLE
[BUG]: Condition context filter created via "Occurring values" in Properties view is not valid

### ISSUE THREAD

**Issue by JohannaOtt** [halestudio/hale#1104]
**Describe the bug**
When creating a condition context on a type using an occurring value from the Properties and editing it, the filter is not valid.

**To Reproduce**
1. Load the dataset attached to hale studio (using the XPlanGML 5.1 schema from the presets)
[3Aenderung.zip](https://github.com/halestudio/hale/files/14192739/3Aenderung.zip)
2. Determine the occurring values of `RP_Landwirtschaft.id`
3. Right click on the value in the Occurring value list and chose "Create condition on parent RP_Landwirtschaft"
4. Right click on the new condition context and chose "Edit condition context"
5. The filter is invalid according to the dialogue 
6. When adding quotation marks around `id`, the filter is valid and still working (filter being `"id" = 'GML_517b396a-2685-11ec-962e-1f829c9bb818'`).

**Expected behavior**
I would expect the filter created by the functionality in the Occurring values list to be valid

**Screenshots**
![grafik](https://github.com/halestudio/hale/assets/34163838/ee58ee3f-13aa-4218-89b9-bc6f0554f4d1)

**Additional context**
The filter created for other attributes is valid. I assume that the original filter is invalid because of "id" being involved. According to the [documentation](http://help.halestudio.org/latest/topic/eu.esdihumboldt.hale.doc.user/html/reference/cql_filter.html?cp=0_7_1), it needs the quotation marks but those should then also be used when creating the filter from the Occurring values.

**Comment by florianesser** [comment]
Can be challenged with [this build](https://github.com/halestudio/hale/pull/1184#issuecomment-2124607748).

**Comment by JohannaOtt** [comment]
Tested with the workflow described above and the filter is not reported invalid in the dialogue any longer.
@florianesser If I understood the discussion in the related PR correctly, the issue will be closed with the PR and I therefore leave it open now?

**Comment by florianesser** [comment]
Thanks for the challenge, @JohannaOtt!

> If I understood the discussion in the related PR correctly, the issue will be closed with the PR and I therefore leave it open now?

Yes, exactly. Now that you've challenged it, I will merge the PR which will close the issue.
