### ISSUE TITLE
[BUG]:) The issues of GML files, when we are using INSPIRE Transport Networks theme schemas (v 5.0) in HALE Studio 5.1

### ISSUE THREAD

**Issue by AurelijaStu** [halestudio/hale#1131]
Dear Wetransform team,

we have a question regarding the updated INSPIRE schemas and the updated version of HALE Studio.

When we were updating data transformation models using the updated (v.5.0) INSPIRE schemas, we had noticed differences in how the GML file is exported by HALE Studio 3.5.0 and HALE Studio 5.1.

For example,
When we import scheme  https://inspire.ec.europa.eu/schemas/tn-ro/5.0/RoadTransportNetwork.xsd to Hale Studio 5.1, the properties of attribute  „beginlifespanVersion“ is specified this way:

![image](https://github.com/halestudio/hale/assets/79690432/16649398-7909-4daa-88c2-4a6ed5fc1e93)
![image](https://github.com/halestudio/hale/assets/79690432/847c7604-7b45-4026-a964-e85437b8aff1)

When we import the same scheme  to  Hale Studio 3.5, the properties of attribute „beginlifespanVersion“ is specified as expected:

![image](https://github.com/halestudio/hale/assets/79690432/0e0a4998-edb7-44f1-9cf1-f51606ee2c7b)
![image](https://github.com/halestudio/hale/assets/79690432/1978bcdb-ed77-45f5-bf68-f7e133e86f05)

The differencies (which are related with referencies to xml schemas) are noticeable when we are using the schemas listed below:

- https://inspire.ec.europa.eu/schemas/tn-ra/5.0/RailwayTransportNetwork.xsd
- https://inspire.ec.europa.eu/schemas/tn-ro/5.0/RoadTransportNetwork.xsd
- https://inspire.ec.europa.eu/schemas/tn-w/5.0/WaterTransportNetwork.xsd

These differencies are also visible in reports of INSPIRE ETF validator.

If  we import the schemas (v.5.0)  to Hale Studio 3.5.0 and export GML file, when ETF validator does not show errors.
We  attached INSPIRE ETF validator report (name: ValidationResults_HaleStudio_3_5_Road_sample.html)  and gml file (name: HaleStudio_3_5_Road_sample.gml).

If we import schemas (v.5.0) to Hale Studio 5.1.0 and export GML file, when ETF validator shows errors which probably are related with some .xsd elements and their referencies to xml schemas (except error which are related with geometry. This error is because we are testing sample of data).
We  attached INSPIRE ETF validator report (name: ValidationResults_HaleStudio_5_1_Road_sample.html) and gml file (name: HaleStudio_5_1_Road_sample.gml).

[files.zip](https://github.com/halestudio/hale/files/14612511/files.zip)

Could you please have a look if these issues are related to the HALE Studio update, or it could be an another reason of this?

**Comment by stempler** [comment]
Thank you for the report @AurelijaStu !

hale studio includes offline versions of the schemas, but there seems to be a discrepancy between what is included in hale studio and what is served on the INSPIRE website.
The schemas used in hale studio use the current version of the schemas from the GitHub repository at the time of release. There the schemas look correct, e.g. [RoadTransportNetwork.xsd](https://github.com/INSPIRE-MIF/application-schemas/blob/main/schemas/tn-ro/5.0/RoadTransportNetwork.xsd), so we will need to check why that is not properly reflected (and provide a new version with the update).

As workaround you can delete the file `eu.esdihumboldt.util.resource.schemas.inspire_2024.2.21.bnd-8IYMsg.jar` in the `plugins` folder of your hale studio installation.

**Comment by stempler** [comment]
Fixed in 5.2.0
