### ISSUE TITLE
Control Winding Order as Transformation Function

### ISSUE THREAD

**Issue by thorsten-reitz** [halestudio/hale#122]
Provide the Control Winding Order functionality currently implemented as a GML encoding option as a transformation function as well.

**Comment by stempler** [comment]
Any background on this? Do you have concrete use cases in mind where this would be needed?

**Comment by thorsten-reitz** [comment]
I got a request via the INSPIRE thematic clusters forum with the following rationale:

> I am asking this because if storing counterclockwise spatial data in a PostGIS database and if records will be added or edited with qGIS for example, (or if a shapefile is imported in PostGIS) then only the added/edited records will be stored clockwise, so in the same table will have both types> clockwise and counter clockwise. Even if  PostGIS and qGIS have no problem with this, still a mapping problem exist.

**Comment by stempler** [comment]
Makes sense in that case. At least if PostGIS by default does not assume a specific winding order that we are unaware of.

> It's also a pretty common transformation function in other spatial ETL software, so I am not surprised people expect such functionality.

Well in hale right now using this transformation function will prevent the user from doing anything else with the geometry.

**Comment by thorsten-reitz** [comment]
PostGIS allows - via a constraint - to control which winding order is used, but doesn't do automated conversion AFAIR.

I am aware of the limitation you mention, which is part of the reason why we implemented it first as a Writer Option. We could also go a third way: Provide the functionality as a helper function for Groovy Functions/Custom Functions.

**Comment by stempler** [comment]
> PostGIS allows - via a constraint - to control which winding order is used

If we can determine this for a geometry or geometry column we could also apply that in the PostGIS geometry handling on hale side (like the CRS conversion).

**Comment by thorsten-reitz** [comment]
Here's some info on the PostGIS functions:

http://postgis.net/docs/ST_ForceRHR.html
http://postgis.net/docs/ST_ForceLHR.html

Not sure how we could extract their usage. Also, they seem to fail for some large and/or complex polys.
