### ISSUE TITLE
Problem when importing a CSV file as source schema

### ISSUE THREAD

**Issue by blitzfrayret** [halestudio/hale#1268]
**Describe the bug**
When importing the csv file of the dataset 'BONARES-signal.ID_7024_FORST_NOTWORKING.csv' with the wizard 'Import source schema', at the step 'Typename Settings' the button 'Finish' is not actionable. 

**To Reproduce**
1. Go to 'File' ->'Import' -> 'Source schema'
2. Browse directories to select the file '[BONARES-signal.ID_7024_NOTWORKING.csv](https://github.com/user-attachments/files/17398419/BONARES-signal.ID_7024_FORST_NOTWORKING.csv)'
3. Click on  'Next'
4. Click on  'Next'
5. Click on  'Next'
6. At the 'Typename Settings' step, the button 'Finish' stays unactionable.

**Expected behavior**
6. At the 'Typename Settings' step, the button 'Finish' should be actionable to import the file.

**Screenshots**
If applicable, add screenshots to help explain your  problem.

![issue_Hale_import](https://github.com/user-attachments/assets/b36b9d96-9a47-45c2-8708-5e3e8136ef8a)

**To get around the problem**
Open the file BONARES-signal.ID_7024_NOTWORKING.csv in Excel, copy the content, paste it in another Excel file, export it as csv file '[Classeur1.csv](https://github.com/user-attachments/files/17398466/Classeur1.csv)'. This file can be imported with Hale studio.

**Comment by blitzfrayret** [comment]
This bug occurs when using version 5.3.0 of Hale Studio on Windows.

**Comment by florianesser** [comment]
@blitzfrayret Thanks a lot for reaching out! The button "Finish" should be available when you change the value of the Typename input field at the top of the dialog (e.g. to just "ID_7024_FORST_NETWORKING"). A name with dots (`.`) in it is not allowed, that's why the error message "Please enter a valid Type Name" is shown in the header.

**Comment by florianesser** [comment]
@blitzfrayret Renaming the file is not necessary, hale»studio can work with files that have dots in it. However, type names in schemas are not allowed to have dots in it. So if, like in this case, a file with dots in the file name is imported, the type names automatically derived from the file name needs to be edited, as shown in the screenshots.

![grafik](https://github.com/user-attachments/assets/0efd13c3-88ad-4843-b54c-f86f349baf39)

![grafik](https://github.com/user-attachments/assets/444519a0-ec89-4369-8d6a-5c42956541b8)

**Comment by blitzfrayret** [comment]
Thank you for this information about the dot in the Type name.
