### ISSUE TITLE
[BUG]: Validation is not failing if a mandatory element is provided with a nilReason value

### ISSUE THREAD

**Issue by JohannaOtt** [halestudio/hale#1280]
Version 5.4.0.SNAPSHOT
Build 202410251955
Revision 91570048d1eea6e209fdcecf0f2147f7becea232

**Describe the bug**
When assigning a nilReason to an element that is mandatory (cardinality >=1 & NillableFlag = false) and marked with a red asterisk, the file validation is not failing.

**To Reproduce**
1. Open the alignment attached 
[1280.zip](https://github.com/user-attachments/files/17800562/1280.zip)
2. Check the elements GeophProfile.projectedGeometry and GeophProfile.shape. They both have a red asterisk marking them as mandatory but they are empty and only a nilReason attrtibute is provided for them
3. Check the instance validation result - it is successfull

**Expected behavior**
I would expect the instance validation to fail as no value is provided for the mandatory elements.

**Screenshots**
![grafik](https://github.com/user-attachments/assets/05c38f5e-5ec7-4dd8-804b-e81cacaacaa2)

**Comment by stempler** [comment]
In this case the `shape` element needs to be present. It does not have a simple value, instead it can have child elements (`AbstractGeometry` subsitution group). But these are optional. So the `shape` element must be provided, but it may be empty.
By providing a value for the `nilReason` attribute, the `shape` element is created implicitly.
So in my view like this it is valid.

**Comment by JohannaOtt** [comment]
@stempler Thank you for assessing that. I close the issue accordingly.
