### ISSUE TITLE
Read a database schema from an SQL file

### ISSUE THREAD

**Issue by thorsten-reitz** [halestudio/hale#152]
Instead of always having to connect to a DBMS, enable hale to read a schema directly from a *.SQL file.

**Comment by thorsten-reitz** [comment]
Frist Priority would be PostGresSQL.

**Comment by JohannaOtt** [comment]
@florianesser Isn't that already implemented or am I misunderstanding the expectation?

**Comment by JohannaOtt** [comment]
@florianesser @stempler Isn't that already implemented or am I misunderstanding the requirements?
