### ISSUE TITLE
Support for formatted number output

### ISSUE THREAD

**Issue by thorsten-reitz** [halestudio/hale#166]
Currently, hale uses java standard number serialization, but in many situations a defined number format, with a fixed number of decimals before and after the point, potentially with leading zeroes is required. It should be possible to define this for formats that don't have a constraint expressing that (many databases do, but XSD doesn't). The preferred implementation for this is as a constraint on the property, with a writer configuration option.

DoD:
- Provide control for this in XML only.

**Comment by thorsten-reitz** [comment]
Check how to enforce serialization to formatted numbers first -> Spike

**Comment by stempler** [comment]
We analyzed this and found that writing the coordinates of geometry objects is handled in a central place. So adding support for custom number formatting there would be quite easy. My understanding of the original use case was that this is mainly related to the representation of geometries.

@thorsten-reitz Is that correct and would an implementation that targets the encoded geometries be sufficient?

**Comment by thorsten-reitz** [comment]
@stempler yes, that is correct and would be OK for now. I don't think a global setting makes sense for individual fields otherwise. Is there an XML type like BigDecimal that allows control over the serialisation of numbers?
