### ISSUE TITLE
Show only mandatory properties in Schema Explorer

### ISSUE THREAD

**Issue by thorsten-reitz** [halestudio/hale#175]
Add an Option to source and target schema explorer to hide optional properties

**Comment by thorsten-reitz** [comment]
@stempler  Minor quibble, when I toggle to show only mandatory properties, "location" is still included for any GML feature type, though it's 0...1. Does that make sense

**Comment by stempler** [comment]
@thorsten-reitz  @arunverma87 I think groups are not included in the check, so that should be added.

**Comment by stempler** [comment]
I think the icon could be improved. Right now it does not really hint at that it is related to optional/mandatory properties.

As the icon is active when optional properties are shown, it could symbolize optional properties.

**Comment by thorsten-reitz** [comment]
I agree. What about picking up the red star that we use to indicate mandatory properties?

**Comment by stempler** [comment]
Yes, that would work. But it would be different to the other filters, where the icons symbolize what is currently shown that is hidden when you deactivate it.

**Comment by thorsten-reitz** [comment]
Works now.
