### ISSUE TITLE
Add MS SQL Server Reader

### ISSUE THREAD

**Issue by thorsten-reitz** [halestudio/hale#183]
Add a schema and an instance reader to read from MS SQL Server databases. Support Geometry and Geography data types, as well as arrays. Read out as many constraints as possible from the schema. In case of Arcs, interpolate them as described in #181.

DoD:
- Automatically test with MS SQL Server 2012 or later

**Comment by thorsten-reitz** [comment]
@doemming Do you have any know issues related to this ticket? I believe there was still the question of some axis order/SRS definition problems.

**Comment by doemming** [comment]
@thorsten-reitz It has turned out that the issue was not related to the reader, but to the data in the related project.

**Comment by thorsten-reitz** [comment]
Ok, I remember that issue, so I am closing this one.
