### ISSUE TITLE
Provide standard function for ID generation

### ISSUE THREAD

**Issue by thorsten-reitz** [halestudio/hale#184]
Generalize rules as defined by the AdV to provide  a general ID function. Provide options to either generate an ID or a reference. Remove the old Inspire ID function. Main goal is to provide IDs for XML/GML.

**Comment by stempler** [comment]
Link regarding explanation template engine for Markdown explanations:
http://docs.groovy-lang.org/latest/html/documentation/template-engines.html#_gstringtemplateengine
