### ISSUE TITLE
Provide an augmentation function to assign values from a collector

### ISSUE THREAD

**Issue by thorsten-reitz** [halestudio/hale#185]
This function allows assigning values to any target element from any collector defined previously, either in a Groovy Script or in a "Define Collector" augmentation function (see #209). 

Workflow:

1. Click on any target property element
2. After confirmation of the Cell entities, set which defined collector to use 

Use Cases:

* Collect and create references in GML

**Comment by florianesser** [comment]
Feature build: https://builds.wetransform.to/job/hale/job/hale~publish(master)/200/

**Comment by thorsten-reitz** [comment]
LGTM
