### ISSUE TITLE
Add Spatial Join Function

### ISSUE THREAD

**Issue by thorsten-reitz** [halestudio/hale#187]
Allow joins based on a defined spatial relationship between selected geometries of two object types, Support at least the "contains", "equals" and "touches" operations.

**Comment by florianesser** [comment]
[Feature build](https://builds.wetransform.to/job/hale/job/hale%7Epublish(master)/252/)

**Comment by florianesser** [comment]
[Feature build](https://builds.wetransform.to/job/hale/job/hale%7Epublish(master)/253/)
