### ISSUE TITLE
Paginate/Partition Requests to WFS as a data source

### ISSUE THREAD

**Issue by thorsten-reitz** [halestudio/hale#188]
When performing "Transform External Data" or "Import Source Data", hale should partition requests, e.g. by using the WFS 2.0 pagination capabilities or by using WFS 1.1.0 vendor-specific parameters.

Ideally, hale first requests `resultType=hits`, and then uses `&startIndex=0&maxFeatures=500` for individual requests. This feature might require the user to select the type of WFS (Geoserver or deegree, ...)

**Comment by florianesser** [comment]
Feature build: https://builds.wetransform.to/job/hale/job/hale~publish(master)/185/

**Comment by stempler** [comment]
New build will be https://builds.wetransform.to/job/hale/job/hale~publish(master)/189/

**Comment by florianesser** [comment]
New feature build will be https://builds.wetransform.to/job/hale/job/hale%7Epublish(master)/191/

**Comment by thorsten-reitz** [comment]
Tested build 191.
Looks good to me.
