### ISSUE TITLE
Improve Rendering Performance for large Polygons/Lines

### ISSUE THREAD

**Issue by thorsten-reitz** [halestudio/hale#197]
Rendering in the map views gets really slow when large polygons with a high vertex count need to be rendered, effectively blocking usage of the view.

It might also help to be able to manually stop rendering (to clear the queue) and then to start it again.

**Comment by thorsten-reitz** [comment]
Two possible solutions comes to mind, both of which could be combined and utilize the new preprocessor capabilities:

1. generalize the very large linestring or polygon and use that for map view rendering; it would even be possible to create multiple generalizsations and then use only those appropriate to the selected zoom level in the map view;
2. partition the geometry internally into multiple geometries, so that each one can be rendered by itself.

The latter is more complex in the case of a polygon/surface, but could be handled like how [i3s](https://github.com/Esri/i3s-spec) deals with large polygons: 

1. The polygon is split into partitions along the areas in the spatial index as long as a maximum number of vertices remains in one area/tile. 
2. For each of these areas, a new polygon is created, whose edges are flagged as either belonging to the original polygon or as being edges added to connect original edges.
3. When renderingin the polygon, the outline is only rendered fo all edges flagged as an original edge.

**Comment by stempler** [comment]
For the second possibility an easy to implement possibility might be to calculate the intersection of the tile bounding box and the actual geometry (at least if the geometry actually exceeds the bounds).

**Comment by thorsten-reitz** [comment]
The only downside of caclulating the intersection with a very large polygon is that it can take very long as well. What we did was just check which segments of a Polygon intersect with the tile bounding box and then create a new polygon from the resulting fragments. This required special treatment of two cases:

1. Segments that intersect (and are not contained by) the Tile BB need to be cut;
2. Segments that belonged to inner rings need to be treated separately.
