### ISSUE TITLE
Provide UI helper to insert project variables

### ISSUE THREAD

**Issue by thorsten-reitz** [halestudio/hale#198]
In all functions that allow usage of project variables, it should be possible to directly insert such variables in a similar way as how variables are inserted in the formatted string function.

**Comment by thorsten-reitz** [comment]
Is there already a build to test that? 

General suggestion to make my life easier ;): when adding the "to be tested", add a comment pointing to the build that includes the feature.

**Comment by florianesser** [comment]
Not yet, I will add a link here as soon as it's done.

**Comment by thorsten-reitz** [comment]
Looks good to me!
