### ISSUE TITLE
Support other Arc representations for GML for Arc interpolation

### ISSUE THREAD

**Issue by stempler** [halestudio/hale#212]
Improvement regarding #181 

Right now only Arc elements are supported to be interpolated on import, not ArcByBulge, ArcByCenterPoint, ArcStrings and any other Arc representations.

**Comment by arunverma87** [comment]
Now, Types like ArcString, Circle, ArcByCenterPoint and CircleByCenterPoint are to be interpolated on import.

**Comment by thorsten-reitz** [comment]
As far as I can see based on the tests and the limited real-world data we have, this works.
