### ISSUE TITLE
Arc interpolation: consistent points between different kinds of geometries

### ISSUE THREAD

**Issue by stempler** [halestudio/hale#219]
Improvement for #181 

The current Arc interpolation implementation may lead to topological inconsistencies in respect to other kinds of geometries.
To deal with this there should be two modes:
1. Keep all original points, e.g. Arc start- and end-points (**default**)
2. Move all points (of all geometries) to the interpolation grid

**Comment by stempler** [comment]
The current implementation of the interpolation will result in problems when assembling LinearRings, with errors like this: "Points of LinearRing do not form a closed linestring".

**Comment by thorsten-reitz** [comment]
Seemed to work for the data sets I have available.
