### ISSUE TITLE
Conditional Existence validation check

### ISSUE THREAD

**Issue by thorsten-reitz** [halestudio/hale#222]
To improve advanced validation, it should be possible to define and validate a rule that tests conditional Existence, i.e. performs checks of the type `"If property X exists (is not null), then property Y also has to exist"` or `"If property X exists (is not null), then property Y must not exist"`. 

I see two ways of implementing this:

1. Adding a schematron validator
1. Extending the internal validator (which would also require UI elements to define the additional contraints)

If the second approach is selected, I'd propose to use the Properties view and add a new tab for "Additional Constraints" where those may be defined.

**Comment by arunverma87** [comment]
For example,
One can write schematron rules as below,
case 1: `"If property X exists (is not null), then property Y also has to exist"`

`<sch:assert test = " (not(mudab:controlChartPeriodStartDate)) or 
                                  (mudab:controlChartPeriodStartDate and mudab:controlChartPeriodEndDate)"> 
     if controlChartPeriodStartDate exist then controlChartPeriodEndDate should also exist, if  controlChartPeriodStartDate does not exist then rule can be omitted.
</sch:assert>`

case 2: `"If property X exists (is not null), then property Y must not exist"`

`<sch:assert test = " (not(mudab:controlChartPeriodStartDate)) or 
                                  (mudab:controlChartPeriodStartDate and not(mudab:controlChartPeriodEndDate))" > 
     if controlChartPeriodStartDate exist then controlChartPeriodEndDate should not exist, if  controlChartPeriodStartDate does not exist then rule can be omitted.
</sch:assert>`

**Comment by arunverma87** [comment]
There are some good resources available for schematron rules writing,

1. [Oreilly Community](http://broadcast.oreilly.com/2009/03/post-1.html)
2. [Sample Code](https://dev.pageseeder.com/reference/sample_code/schematron.html)
3. [validating XML using XSLT](http://www.ldodds.com/papers/schematron_xsltuk.html)

**Comment by thorsten-reitz** [comment]
OK thanks, I'll close the issue when I could test these rules (or similar ones) in hale studio.
