### ISSUE TITLE
Remove or reduce Arc interpolation default value warning

### ISSUE THREAD

**Issue by stempler** [halestudio/hale#227]
The message "Value of Max positional error parameter, for interpolation operation, is not valid. Default value has been taken." may appear a lot of times in the log when loading geometries w/ Arcs.

My suggestion would be to either emit it only once for a given import (reader?) or to remove the message.

**Comment by stempler** [comment]
refs #181

**Comment by arunverma87** [comment]
fix added in #230

**Comment by thorsten-reitz** [comment]
Seems to be OK (tested with build 153 and Koblenz data)
