### ISSUE TITLE
Remove Errors on loading Pro Plugins

### ISSUE THREAD

**Issue by thorsten-reitz** [halestudio/hale#235]
Currently, after loading the pro plugins, there are six error messages in the log:

```
eclipse.buildId=unknown
java.version=1.8.0_91
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en_US
Command-line arguments:  -os win32 -ws win32 -arch x86_64 -clean

org.eclipse.equinox.p2.publisher.eclipse
Error
Thu Dec 01 11:25:50 CET 2016
Unable to acquire PluginConverter service during generation for: C:\wetransform\var\HALE-3.1.0.20161129\dropins\oracle.database_1.1.0-SNAPSHOT\eclipse\features\oracle.database_1.1.0.SNAPSHOT.jar.
```

Since these don't seem to have any practical implications, I would much rather have one message akin to "hale pro plugins loaded and licensed successfully: Oracle Reader/Writer, FileGeodatabase Reader, ..."

**Comment by stempler** [comment]
I think we discussed that at some point already. The messages are internally from Eclipse. I don't know if there is a fix already, there are a lot of Eclipse bugs related to that floating around (e.g. [Bug 437466](https://bugs.eclipse.org/bugs/show_bug.cgi?id=437466)).

Even if it is fixed that would require an update to an Eclipse version newer than Mars or using a patched bundle.

**Comment by thorsten-reitz** [comment]
Yes, I remember we discussed that, I did want to have it in the issues list though, because it is a bit confusing, so people trying out the pro plugins first impression is that they don't work..

**Comment by thorsten-reitz** [comment]
Is there any way to filter those particular issues higher up in the stack? Or do they got from eclipse directly to the log? Also, the messages might be less relevant if the success message I suggested above was also logged.

**Comment by thorsten-reitz** [comment]
Ok, I remember that issue, so I am closingthis one.

**Comment by florianesser** [comment]
@thorsten-reitz Can you confirm that this is no longer an issue with the new plugin installation method (i.e. via an update site)?

**Comment by thorsten-reitz** [comment]
LGTM.
