### ISSUE TITLE
Schematron validator includes local Jars

### ISSUE THREAD

**Issue by stempler** [halestudio/hale#254]
The schematron validator currently inludes Jars as a local classpath. This may cause problems when the hale artifacts are used outside OSGi. This should be evaluated and fixed if needed.

Problems with including the schematron dependencies via the target platform lie mainly in a problem resolving resources. It is not possible to use a custom resolver (schema-utils API) and adding mechanisms so the resources might be found (e.g. buddy policies) are problematic because the xml-resolver bundle that tries to load the resources is provided both by the hale platform and Eclipse update sites.

**Comment by thorsten-reitz** [comment]
@florianesser can you please validate if this main question is if this is a problem for execution via hale-cli (non-OSGi)? otherwise this would be a non-issue is for.

**Comment by florianesser** [comment]
With the changes of halestudio/hale-cli#24, Schematron validation works for me in hale-cli.
