### ISSUE TITLE
Support for multiple post-encoding validators

### ISSUE THREAD

**Issue by stempler** [halestudio/hale#256]
Right now it is only possible to configure one post-encoding validator after exporting data or running a transformation via the CLI.
It should be supported to have multiple validators, for instance to do XML Schema validation and check Schematron rules on a created XML file.

There are three workflows that need to be taken into consideration:
- Exporting data from hale studio
- Running a transformation on external/project data in hale studio
- Running a transformation via the CLI

**Comment by thorsten-reitz** [comment]
Looks good to me.
