### ISSUE TITLE
Fix Arc Interpolation

### ISSUE THREAD

**Issue by thorsten-reitz** [halestudio/hale#263]
The current implementation is directional and can generate gaps/overlaps.

**Comment by stempler** [comment]
Build see https://builds.wetransform.to/job/hale/job/hale~publish(master)/186/

**Comment by thorsten-reitz** [comment]
This particular issue is fixed, though the general quality of the interpolation can be improved. We'll close this issue for now and will after customer feedback open a new one for a new interpolation method if necessary.
