### ISSUE TITLE
Improve behaviour on missing Bursa-Wolf parameters

### ISSUE THREAD

**Issue by thorsten-reitz** [halestudio/hale#281]
During export of a GML FeatureCollection with a configured reprojection, Geotools throws an exception with the text "Missing Bursa-Wolf Parameters".  More Information is available here: http://docs.geotools.org/stable/userguide/faq.html

We've had this error reported by users at least 10 times by now. I therefore propose to catch this error and ask for complete CRS information, and to store it so that the PRJ info is ignored henceforth.

**Comment by florianesser** [comment]
[Feature build](https://builds.wetransform.to/job/hale/job/hale%7Epublish(master)/316/)

**Comment by thorsten-reitz** [comment]
I hit a problem with one of my Ukraine Shapefiles while testing that. Will provide the data.

**Comment by florianesser** [comment]
@thorsten-reitz [The latest RC build](https://builds.wetransform.to/job/hale/job/hale%7Ebuild(staging)/8/) also contains a fix that should prevent the axis flip.

**Comment by thorsten-reitz** [comment]
LGTM.
