### ISSUE TITLE
Upload hale project to haleconnect.com

### ISSUE THREAD

**Issue by thorsten-reitz** [halestudio/hale#292]
When logged in with my haleconnect.com account (see #291), I want to be able to directly share a transformation project on haleconnect.com.

Workflow:
1. Go to File -> Share...
2. In the dialogue, provide/edit Title and Description, and chose visibility of the resource (private, organisation, public), click "next"
3. Choose which resources to upload with the project: source/target schema, data/data excerpt, click "next" or "finish"
4. Choose whether you want to notify someone, you can pick "Support" and/or any user visible to you. In addition, you can provide a message to those you notify. Click "Finish". Hale studio displays a progress dialogue and provide a confirmation with a link to the created project after completing the upload.

Definition of Done:
1. Add new File -> Share... Wizard with steps as explained above
2. File -> Share option should be greyed out if user is not logged in (see #291)

Enhancements: 
1. Automatically identify related resources that are already on haleconnect.com, in particular schemas, and don't offer those as resources to be uploaded

**Comment by stempler** [comment]
An alternative notion to sharing projects to haleconnect would be saving them there. That is also in relation to #293 - if we load a project from haleconnect.com it should be easy to save it again.

**Comment by thorsten-reitz** [comment]
I think it is important to make Sharing an explicit action. Nonetheless, adding an alternative workflow via the "Save Alignment Project as..." path might make sense.

**Comment by florianesser** [comment]
[Feature build](https://builds.wetransform.to/job/hale/job/hale%7Epublish(master)/240/)
