### ISSUE TITLE
Access and load transformation projects from haleconnect.com

### ISSUE THREAD

**Issue by thorsten-reitz** [halestudio/hale#293]
As a hale studio user, I need to access and download transformation projects available on hale connect based on my haleconnect.com user account (#291).

Workflow:
1. Go to File -> Open Alignment Project...
2. Click on the "From haleconnect.com" tab
3. Click into "Project" text input to bring up project search
4. In the project search, filter by keyword and Ownership ("My Projects", "My Organisation's Projects, All Projects"). Pick a project and click "Open".
5. If ownership permits, choose whether changes should be saved locally or uploaded. If saved locally, as for a filename/location where to store the file. Click "Finish"

Definition of Done:
1. Remove the "New Project from Template..." option
1. Implement new tab to find and load projects from haleconnect.com

Enhancements:
1. Add a badge to the haleconnect.com tab showing the number of available projects.
1. Directly uploading changes could be an enhancement

**Comment by stempler** [comment]
For loading the project I see basically two options:

- Download the project and load it from local files
- Directly load it from the remote location

And an advanced third option: Clone to a local git repository

**Comment by thorsten-reitz** [comment]
@stempler What about this approach to handle this?

1. The user owns the project they download: A copy of the project is downloaded to the workspace, but this is not made transparent to the user. All changes on "save" are uploaded to the remote project by default. If the internet conection is not available, they are persisted to the local project only.
2. The user doesn't own the project they access: A copy is made to the haleconnect.com account of the user, and then the process is made as in (1). 

To save a project from haleconnect.com fully locally, "Export to Archive/Save as archive" could be used.

**Comment by stempler** [comment]
Sounds good to me. What we should think about is how we want to deal with included resources. It's desirable to reduce the traffic as much as possible. Should it be configurable to store data there? Because especially when working together in a project it can be helpful to have at least a data sample accessible.

**Comment by florianesser** [comment]
[Feature build](https://builds.wetransform.to/job/hale/job/hale%7Epublish(master)/240/)
