### ISSUE TITLE
Spatial index for data sources

### ISSUE THREAD

**Issue by stempler** [halestudio/hale#300]
As part of the data source processing integrate building a spatial index. The index should store `InstanceReference`s by bounding box. The basic capabilities are:

- retrieve `InstanceReference`s by bounding box
- retrieve `InstanceReference`s by bounding box and type

Access to the index should at least be available in Groovy transformation functions.

**Comment by stempler** [comment]
In hale studio, the index should only be created once (or when the source data is reloaded).

Investigate if we can use that opportunity to introduce a more general concept of source data processing/indexing as prerequisite for the transformation.

**Comment by thorsten-reitz** [comment]
I tested the [build](https://builds.wetransform.to/job/hale/job/hale%7Epublish(master)/205/), seems to work OK. Should we close this ticket and put any open work into enhancement issues?
