### ISSUE TITLE
Replace "HALE" with "hale studio"/"hale" throughout the application

### ISSUE THREAD

**Issue by florianesser** [halestudio/hale#310]
- [x] Update help documents and TOCs
- [x] Change the application title to "hale studio"
- [x] Update macOS installer

**Comment by thorsten-reitz** [comment]
It should be hale studio when it is explicitly about this application, and hale if it's more general, e.g. "hale alignment", "hale transformation function".

**Comment by florianesser** [comment]
macOS installer has `HALE` title. Also missing a wetransform copyright notice (shows only IBM et al.)

![screen shot 2017-04-28 at 14 10 06](https://cloud.githubusercontent.com/assets/1867607/25528321/86c6e7d4-2c1d-11e7-93ef-e6848e50d80d.png)

**Comment by florianesser** [comment]
New application info on macOS: 
![2017_05_03_17_08_44_macos_hale_studio](https://cloud.githubusercontent.com/assets/1867607/25700561/8e9b0d64-30c8-11e7-8221-97f298d020ea.png)

**Comment by thorsten-reitz** [comment]
Fixed HALE mentions in the Repo README. Also, almost all the links there were outdated.

**Comment by florianesser** [comment]
[Build](https://builds.wetransform.to/job/hale/job/hale%7Epublish(master)/252/)
