### ISSUE TITLE
Issues with spaces in file names in project archives

### ISSUE THREAD

**Issue by stempler** [halestudio/hale#311]
Loading a project archive that includes a file that originally had a space in its name seems to fail (file is not found). Could be related to the URL encoding.

**Comment by florianesser** [comment]
Is there an example available where this happens? My attempts to create a minimal example on Windows all seem to work (I didn't test all types of project resources, though).

**Comment by stempler** [comment]
I think Jose had an example where this happens. From what I remember the path / file name that was looked for was URL encoded. Maybe it was a case where a web resource (containing a space) was included in the project. Might also be that there is a difference in file names or folders having a space.

**Comment by florianesser** [comment]
[Build containing fix](https://builds.wetransform.to/job/hale/job/hale%7Epublish(master)/237/)

**Comment by florianesser** [comment]
Tested successfully by Jose w/ his own example.
