### ISSUE TITLE
Update mapping documentation for help example projects

### ISSUE THREAD

**Issue by stempler** [halestudio/hale#312]
The example projects in the help have their mapping documentation generated as part of the help. This uses the deprecated HTML mapping documentation. This should use the new HTML+SVG mapping documentation if possible. If not, the mapping documentation should be removed.

**Comment by stempler** [comment]
The documentation integration in the help is currently also not working.

**Comment by florianesser** [comment]
[Build containing fix](https://builds.wetransform.to/job/hale/job/hale%7Epublish(master)/238/)
