### ISSUE TITLE
Arbitrary SQL queries as data source

### ISSUE THREAD

**Issue by stempler** [halestudio/hale#313]
Based on the existing JDBC database access there should be also the possibility to use a custom SQL query. What needs to be done is:

- support importing an SQL query as schema/type
- support importing data from the database based on that type
- add needed specific UI support

**Comment by thorsten-reitz** [comment]
What enhancements are still open on this issue?

**Comment by stempler** [comment]
Main question is if we want to keep the behavior that we have there right now regarding loading the data (importing the data from the database only once, implying that the same queries are used as specified for the schema and requiring a reload when a new SQL schema type is added).

That also implies how we might deal with possible improvements regarding the possibility to
- adapt the query for loading data
- change the query after initial loading of the data
- change the schema query after initial loading of the schema type

**Comment by thorsten-reitz** [comment]
I've created enhancements and will now close this issue for this milestone.
