### ISSUE TITLE
Deactivate GeoServer integration test for faster hale builds

### ISSUE THREAD

**Issue by stempler** [halestudio/hale#318]
[Up to half the time of the whole unit and integration testing](https://builds.wetransform.to/job/hale/job/hale~pull/437/allure/#timeline/50118b15abf20ba5) seems to be taken up by the GeoServer integration test "Test config archive upload".

Maybe it would be good to have this test not running, at least by default.

I see three possibilities:
- we disable the test (`@Ignore`)
- we don't run integration tests when building pull requests
- we create a separate category for long running integration tests that only run for master builds (maybe even apart from the "normal" master build)

Personally I think running integration tests for pull requests is quite valuable, especially when working on JDBC related functionalities.

**Comment by florianesser** [comment]
In all likelihood, the running time of the integration test suite will continue to go up in the future as we add more and more tests. To keep our development cycles (PR->test->(fix)->merge) managable, I'd favour running the integration test suite for master builds only.

I'd also support the idea to have two kinds of master builds (e.g. `dirty` and `integrated`). That way we'd have a quick master build available for feature testing.

**Comment by thorsten-reitz** [comment]
@stempler is this still relevant since the geoserver plug-ins was removed from the main product?
