### ISSUE TITLE
Content Assist for project variables in Regex Analysis Wizard not working

### ISSUE THREAD

**Issue by thorsten-reitz** [halestudio/hale#319]
The content assist to insert project variables into the output format field of the Regex Analysis Wizard is not working. Furthermore, project variables are not evaluated on the "test" action in the same wizard page.

**Comment by florianesser** [comment]
[Build containing fix](https://builds.wetransform.to/job/hale/job/hale%7Epublish(master)/235/artifact/build/target/HALE-3.3.0.SNAPSHOT-win32.win32.x86_64.zip)
