### ISSUE TITLE
Load Data from Arbitrary SQL - Adapt the Schema query for loading data

### ISSUE THREAD

**Issue by thorsten-reitz** [halestudio/hale#325]
When the schema is defined through an arbitrary SQL statement (please refer to #313), it should be possible to edit the query for source data loading so that only a subset of the data is loaded, e.g. limit to a spatial extent or property. Options I see for this from a User perspective:

- add an additional page to the wizard where the original SQL statement can be edited, 
- add a page which allows the specification of a WHERE statement.

**Comment by stempler** [comment]
So that means we exclude the SQL queries from being loaded in the general database data import and handle them separately?

Then we should do that before a release, as this change will not be backwards compatible.

**Comment by stempler** [comment]
As stated in the comment above the approach should be clarified before a release, as the current behavior would not support this approach and the change would not be backwards compatible.
