### ISSUE TITLE
Partition GML/WFS FeatureCollection to multiple files when writing

### ISSUE THREAD

**Issue by thorsten-reitz** [halestudio/hale#331]
Very large GML files are often problematic in all kinds of client/downstream applications, such a QGIS and hale connect.

Thus, add an option to the GML writers to write a FeatureCollection to 1..n files, all in one folder, adding a postfix counter to the filenames. 

Definition of Done:

* Allow the user to set a limit in terms of file size (when exceeded, do not write additional features) or in terms of feature counts per file. 
* Modify all in-document references in `href` attributes so that they point to the right file, ideally without requiring a second pass through the generated files (which could definitely be done when implementing the "features per file" option above).

**Comment by stempler** [comment]
From the description I gather that the existing functionality for splitting into multiple files that is used for instance in the WFS export is not supposed to be used here, right?

Regarding the handling of feature references my question is what we want to support regaeding the further processing of the resulting files?
For instance does hale itself not have any support for these cross-references and also uploading these different files via WFS-T will not work, as references to other files will not be resolvable.

**Comment by thorsten-reitz** [comment]
In principle, maintaining references and consistent state when writing to a WFS-T in many individual transactions would require an analysis of the graph of references between instances, I assume? Based on the type of graph, one of the following would have to happen:

Tree structures or directed acyclic graphs:

1. write root node first
2. incrementally write first-level children pointing to root node
3. incrementally write n-th level children pointing to n-1-th level children
4. Update root element with references to first-level children

Cyclic graphs:

1. identify node withthe highest cardinality and write that
2. Add nodes (in batches) that are once-removed from that center node, with references to the center node
3. Iterate over graph until all nodes are added
4. Update all nodes with additional references

**Comment by thorsten-reitz** [comment]
There is a need to differentiate two use cases:

1. create a set of files for usage as files (e.g. in desktop GIS)
2. create a set of files to be used to fill a deegree service via WFS-T

Additional requirements:

* Clarify: deegree needs special GML ID formats including a FeatureType prefix and generates these on the fly (?)

**Comment by thorsten-reitz** [comment]
minimum implementation: offer current partitioning mechanism (which keeps all objects that have references together in one fragment) and test how that works in various clients.

**Comment by florianesser** [comment]
[Feature build](https://builds.wetransform.to/job/hale/job/hale%7Epublish(master)/267/). This build does not support partitioning when using `Transform external data` or the CLI.

**Comment by thorsten-reitz** [comment]
While the partitioned writing works as intended, it is also slower than before using hale studio 3.3.0. I benchmarked three projects, and found that on average, writing is 4.1 times slower when enabling partitioning. Both cases where partitions can be made and cases where all objects remain in one file take longer to write.

**Comment by florianesser** [comment]
@thorsten-reitz I think a slowdown is to be expected because of the extra partitioning step that evaluates all relations between features. There should, however, be no slowdown when partitioning is disabled.

**Comment by thorsten-reitz** [comment]
Speed is normal when partitioning is entirely disabled, but it is also slow when just one file will be written (either because there are less features than the threshold or because all are connected).
OK, so we might want to do an optimization later on. For the moment, LGTM.
