### ISSUE TITLE
Validation success message before transformation even started

### ISSUE THREAD

**Issue by stempler** [halestudio/hale#346]
I got a validation success message before transformation even started when using the "Transform external data" functionality.

Only the project validator was added for validation, though no rules present. Directly after starting the process I got a message that all validators completed successful. This is a bit irritating as loading the data just started and there was no result yet.

Is validation triggered to early here or is this a special case that has to be handled better?

**Comment by thorsten-reitz** [comment]
+1, I can confirm this behaviour and it also confused me.

**Comment by florianesser** [comment]
It looks like validation is triggered too early here by `InstanceExportWizard.performFinish()`. The actual transformation and export is done by the `TransformDataWizard`, which is only called afterwards.

**Comment by florianesser** [comment]
The same problem occurs when using `Transform project data...`.

**Comment by florianesser** [comment]
[Feature build](https://builds.wetransform.to/job/hale/job/hale%7Epublish(master)/223/)
