### ISSUE TITLE
"Copy geometry" function

### ISSUE THREAD

**Issue by stempler** [halestudio/hale#351]
Especially w/ complex source schemas copying the geometry from source to target may be not straight forward. To some users it is not clear what rules apply there and what function and with which configuration should be used.

So a "Copy geometry" function could simplify that. It should search for the geometry object in the given source property and transfer it.

**Comment by thorsten-reitz** [comment]
Would this function require some specific parameters or could its functionality also be included within the rename function?

**Comment by stempler** [comment]
Adding it to Rename would require adding at least one configuration parameter there. I think introducing a parameter in Rename that results in the function behaving very differently is quite confusing for users.

**Comment by thorsten-reitz** [comment]
What kind of parameters would you add to this function? Would the function also apply conversions (so not just do a 1:1 copy)?

One aspect that I was thinking of was that many users also have problems understanding the "structural rename" parameter, so we might want to revisit how we call/explain that parameter.

**Comment by stempler** [comment]
One use case for this function:

When mapping from one GML schema to another one, the usual approaches to map a geometry are:
- doing a structural rename, often with namespaces ignored (if the geometry property types are compatible regarding the structure)
- picking individual geometry sub-properties (e.g. `Point`, `MultiSurface`) and mapping them with a normal rename

It is most often not possible to do a normal rename (w/o changing any parameters) on the first level geometry property.
