### ISSUE TITLE
Check upstream hale connect project for changes before overwriting

### ISSUE THREAD

**Issue by florianesser** [halestudio/hale#372]
As a hale studio/hale connect user, I want to be made aware of the fact that the hale connect transformation project that I openend in hale studio and now want to re-upload/overwrite has changed since the time of download.

Caveats:

- Change detection will not work if the project was not originally loaded from hale connect
- Such a check may require redownloading the upstream project (which may be slow), unless the `project-service` provides a means of generating a project checksum or sth. similar

**Comment by stempler** [comment]
Should this also take into check where changes were made? e.g. if only changes to the mapping were done, just update the alignment file.

**Comment by florianesser** [comment]
[Feature build](https://builds.wetransform.to/job/hale/job/hale%7Epublish(master)/284/)

**Comment by thorsten-reitz** [comment]
LGTM
