### ISSUE TITLE
Internal CRS definition used for EPSG:3035 has inverted axes

### ISSUE THREAD

**Issue by florianesser** [halestudio/hale#391]
If geometries are transformed to the target CRS EPSG:3035 by hale studio, the resulting geometries have inverted axes compared to a transformation using a custom CRS definition with the WKT from http://spatialreference.org/ref/epsg/3035/html/.

This could probably be fixed by updating the internal EPSG database and/or Geotools. When updating these components, special focus must be placed on verifying that Shapefile support remains intact and the OSGi dependencies.

**Comment by thorsten-reitz** [comment]
Please clarify what impact an Geotools update would have, or whether it would be possible to just update the EPSG database.

**Comment by florianesser** [comment]
@thorsten-reitz @stempler It seems that even if we did update Geotools to the latest version, the problem described in this ticket wouldn't go away, as the CRS definition by EPSG and on spatialreference.org differ also in the latest version of the EPSG database.

If you compare the WKT of [EPSG](http://epsg-registry.org/export.htm?wkt=urn:ogc:def:crs:EPSG::3035) to the one at [spatialreference.org](http://spatialreference.org/ref/epsg/3035/html/), you'll notice that the order of the axes is different.

**Comment by thorsten-reitz** [comment]
@florianesser OK thanks. So can we patch the EPSG database we use?

**Comment by florianesser** [comment]
@thorsten-reitz I'm no longer convinced that this is actually a bug. I checked your e-mail conversation with Wim where he states

> According to Geonovum and http://www.opengis.net/def/crs/EPSG/0/3035 the order should be Y,X wheras the coordinates are now in X,Y.

That the order should be Y,X is consistent with EPSG's definition. This is the WKT definition of 3035 used by hale which also has a Y,X axis order:

```
PROJCS["ETRS89 / LAEA Europe", 
  GEOGCS["ETRS89", 
    DATUM["European Terrestrial Reference System 1989", 
      SPHEROID["GRS 1980", 6378137.0, 298.257222101, AUTHORITY["EPSG","7019"]], 
      TOWGS84[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], 
      AUTHORITY["EPSG","6258"]], 
    PRIMEM["Greenwich", 0.0, AUTHORITY["EPSG","8901"]], 
    UNIT["degree", 0.017453292519943295], 
    AXIS["Geodetic latitude", NORTH], 
    AXIS["Geodetic longitude", EAST], 
    AUTHORITY["EPSG","4258"]], 
  PROJECTION["Lambert_Azimuthal_Equal_Area", AUTHORITY["EPSG","9820"]], 
  PARAMETER["latitude_of_center", 52.0], 
  PARAMETER["longitude_of_center", 10.0], 
  PARAMETER["false_easting", 4321000.0], 
  PARAMETER["false_northing", 3210000.0], 
  UNIT["m", 1.0], 
  AXIS["Northing", NORTH], 
  AXIS["Easting", EAST], 
  AUTHORITY["EPSG","3035"]]
```

This suggests that the axis order used by hale (Y,X) is actually correct and the cause for Wim's original problem (a wrong winding order in GML output) must be something different. I think this needs further investigation.

**Comment by thorsten-reitz** [comment]
According to user feedback, this problem is resolved and indeed lay with an issue in the data.
