### ISSUE TITLE
Enable instance sampling per type

### ISSUE THREAD

**Issue by thorsten-reitz** [halestudio/hale#395]
Especially when working with joins, testing the result is often only possible through disabling instance sampling globally. It would help a lot to have the ability to enable/disable instance sampling per source type, e.g. through the type context menu.

**Comment by florianesser** [comment]
duplicates #240, keeping this version

Comment from 240:

> It would also be really helpful if that was also possible for types with a context, so that only data matching a source context is loaded for instance sampling.
