### ISSUE TITLE
Use pre-calculated index for Merge/Join

### ISSUE THREAD

**Issue by stempler** [halestudio/hale#399]
Right now a Merge or Join each does it's own pass over all instances to build a specific index used for partitioning. The idea here is to do preprocessing once, that collects all index information needed for the alignment (for instance property values for Merge/Join or bounding box for Spatial Join).

For the functionality that is supported in Merge/Join right now, property values would need to be indexed, based on the conditions defined in Merge or Join. It may make sense to also allow storing derived values in the index (e.g. based on a script).

This could be a rough outline of the implementation:

- [x] add generic index to pre-processing of instances
- [x] configure which information to collect in the index based on the alignment (e.g. Merge/Join configuration)
- [x] use index for Merge partitioning
- [x] use index for Join partitioning
- [x] pre-processing should be retriggered in hale studio when there is a configuration change

A point where these changes to handling Merge and Join might cause a problem related to backwards compatibility is Merges/Joins on complex properties. Right now a deep comparison is done on these structures.

**Comment by thorsten-reitz** [comment]
Clarifications:

* Require no special treatment for table transformation preview, instead use samples from live transformation (so we could get rid of the synchronous trafo in the table);
* The alignment should be analysed to determine on which attribute an index would be needed;

**Comment by florianesser** [comment]
Can be tested w/ [this release candidate](https://builds.wetransform.to/job/hale/job/hale%7Epublish(master)/323/).

**Comment by thorsten-reitz** [comment]
LGTM, the feature works, no obvious issues (like misses in joins or the like).

I opened an enhancement ticket to investigate how to get optimal performance from this feature.
