### ISSUE TITLE
Importer can't handle hale connect project-scheme resource URLs

### ISSUE THREAD

**Issue by florianesser** [halestudio/hale#425]
When a project property (e.g. `description`) of a hale studio project is updated in hale connect, subsequently downloaded project archives (via `Download as archive`) can no longer be imported into hale studio. 

hale connect connect changes the `source` properties of project resources from relative paths to absolute `project:/` URLs ~~that cannot currently be interpreted by hale studio~~. (Edit: _they can be handled by `PathUpdate`, see comment below_)

**Comment by florianesser** [comment]
Further analysis showed that `PathUpdate` is unable to resolve the new location of the resource files because hale connect puts different prefixes for the project file and the resources. In this example, the project file URL `project:///org/2/b0f7f1be-7f62-40cf-811f-b82440d1e9b1/raw/project.halex` has three slashes after the scheme whereas the resource URL `project:/org/2/b0f7f1be-7f62-40cf-811f-b82440d1e9b1/raw/resource1/hydroEx.xsd` has only one slash.

**Comment by florianesser** [comment]
[Build](https://builds.wetransform.to/job/hale/job/hale%7Epublish(master)/284/) w/ fix for `PathUpdate`

**Comment by thorsten-reitz** [comment]
LGTM
