### ISSUE TITLE
Allow saving projects to hale connect via "Save as..."

### ISSUE THREAD

**Issue by florianesser** [halestudio/hale#429]
Currently, saving transformation projects via the `Save as...` mechanism is only possible for file targets. Uploading projects to hale connect, therefore, must be done via an export wizard. This has the disadvantage that after such an export the project is not considered being saved by hale and subsequent saves will update the local file the project was loaded from and not the hale connect project (or open a Save as dialog if the project was not previously saved). This enhances the behaviour implemented for #422.

- [x] Refactor `ProjectServiceImpl` to allow saving a project even if no local project file exists
- [x] Allow "Save as..." to hale connect also if current project was loaded from an archive (`.halez`)

**Comment by florianesser** [comment]
[Feature build](https://builds.wetransform.to/job/hale/job/hale%7Epublish(master)/288/)

**Comment by thorsten-reitz** [comment]
LGTM - though we need to check why the master password for the secure storage prompt occurs so often, even during hale startup.
