### ISSUE TITLE
WMS Capabilities from ArcGIS shows no layers

### ISSUE THREAD

**Issue by jdambruch** [halestudio/hale#434]
When i try to add a WMS server from ArcGIS no Layers are shown. Please see GetCapabilities of server attached. It looks like the structure of Layers, in this case just one on the top level is not parsed correctly.

[WMSServer.txt](https://github.com/halestudio/hale/files/1263150/WMSServer.txt)

**Comment by stempler** [comment]
It seems only certain Layers (which are children of a top layer) are parsed from the capabilities. It should be checked how layers can occur in the spec and the handling of the capabilities adapted accordingly.

**Comment by jdambruch** [comment]
Any idea when this will be fixed?

**Comment by thorsten-reitz** [comment]
It's currently an unscheduled bug, so no, not really. Is this a blocker for you in a project?

**Comment by jdambruch** [comment]
Yes, customers cannot use ArcGis-WMS because no layers are shown

**Comment by nmtoken** [comment]
Old issue, but just noting that the ArcGIS GetCapabilities response given above is invalid.  

> Unexpected element "LayerLimit". The content of the parent element type must match "(Name,Title,Abstract?,KeywordList?,OnlineResource,ContactInformation?,Fees?,AccessConstraints?)".
