### ISSUE TITLE
Groovy restriction setting on project load not reapplied correctly

### ISSUE THREAD

**Issue by stempler** [halestudio/hale#444]
Observed behavior:
When a project that requires the Groovy restriction to be lifted is loaded (after a hale restart?), the user is asked if he wants to lift the restriction.
If he says *no* the transformation will run once restricted and then w/o the restriction after the setting has been restored. It would be preferable if the first run is not necessary and the user is not asked for input.
If he says *yes* there are actually three transformation runs. I assume one is triggered by loading the project, one triggered by the restored setting and one by the user choice to lift the restriction.

Test project:
[report-test.zip](https://github.com/halestudio/hale/files/1276515/report-test.zip)

**Comment by florianesser** [comment]
Can be tested w/ this [release candidate](https://builds.wetransform.to/job/hale/job/hale%7Epublish(master)/323/).

**Comment by thorsten-reitz** [comment]
LGTM
