### ISSUE TITLE
Support CQL functions in filter expressions for condition contexts

### ISSUE THREAD

**Issue by florianesser** [halestudio/hale#455]
Allow something like `strToLowerCase(VALUE) like '%m%'` as a filter expression.

**Comment by florianesser** [comment]
Can be tested with [new RC](https://builds.wetransform.to/job/hale/job/hale%7Epublish(master)/326/)

**Comment by thorsten-reitz** [comment]
LGTM

**Comment by thorsten-reitz** [comment]
Was funded by Hansestadt Hamburg.
