### ISSUE TITLE
Improve Mapping View / Alignment View Schema Element Tooltip

### ISSUE THREAD

**Issue by thorsten-reitz** [halestudio/hale#456]
Currentl, the tooltip in the Mapping View / Alignment  View on any schema element doesn't also indicate the type to which the property belongs. This makes it hard in cases e.g. with joins with identical property names to identify which things are joined together.

**Comment by thorsten-reitz** [comment]
Side Note: A user implicitly suggested color-coding schema elements by type, which I think is also a very nice idea.

**Comment by florianesser** [comment]
Comment by @stempler in #568:
> In the alignment or mapping view it is often not clear which type a mapping belongs to, e.g. if inherited or for a Join.
> It would help if that information would at least be available in the tooltip.
