### ISSUE TITLE
relative paths in halex 

### ISSUE THREAD

**Issue by milovanderlinden** [halestudio/hale#464]
I am trying to share halex files through https://github.com/codefornl/INSPIRE/ with others. I noticed that the halex files store absolute paths that are also linux or windows specific. As others will download the halex to an unknown location, I would like to change the entries to the files  to relative paths. Would it be possible to change

`<setting name="target">file:/home/user/workdir/aaa400.halex</setting>
<setting name="source">file:/data/Development/INSPIRE/nwb-wegen/rijkswegen.shp</setting>`

to 

`<setting name="target">file:aaa400.halex</setting>
<setting name="source">file:./rijkswegen.shp</setting>`

It seems to generates al kind of errors when changing these manually.

**Comment by thorsten-reitz** [comment]
Hi Milo,

We saw the issue with incorrect paths as well in the *.halex files published at codefornl/INSPIRE. However, we've never encountered it before and would need additional information to reproduce the issue. Did you do anything special when creating these projects? 

As a note, the absolute path is only used for "last saved at" functionality and is not required to load the projects normally. If you do any manual editing to a halex file, best clear/disable the HTTP cache in the Settings , and then the project should load fully (source schema, source data, target schema).

All the best,
Thorsten

**Comment by stempler** [comment]
1. Usually it is not necessary to change the location because the locations will be relativized to the save location that is also stored for exactly that purpose.
2. The locations manually entered are invalid or point to different absolute paths.
3. To see how valid relative references look like,  select the option to use a relative path when importing a resource in hale

**Comment by stempler** [comment]
Adding to 3.:

Importing with relative path in hale:
![hale-relative](https://user-images.githubusercontent.com/375475/32318195-c8b14ba8-bfb6-11e7-873e-43e5a5cd32ec.png)

Locations then are simple relative paths. If you add `file:` in front that always specifies an absolute URL with the file protocol. Relative URLs don't use a scheme.

**Comment by milovanderlinden** [comment]
That is great! Thank you for the clarification.
