### ISSUE TITLE
Shapefiles: Prefill charset dialog with value from accompanying .cpg file

### ISSUE THREAD

**Issue by florianesser** [halestudio/hale#478]
When importing a shapefile as a schema or instance source, check for an accompanying `.cpg` file and, in case it exists, use the character set specified in it to prefill the charset selection dialog.

**Comment by florianesser** [comment]
[Feature build](https://builds.wetransform.to/job/hale/job/hale%7Epublish(master)/313/)

**Comment by thorsten-reitz** [comment]
LGTM.
