### ISSUE TITLE
keep checkbox "skip first line" in import source data checked when type is selected

### ISSUE THREAD

**Issue by JohannaOtt** [halestudio/hale#498]
in import source data --> CSV --> type settings

right now the checkbox is checked by default when entering that page of the wizard but is unchecked as soon as a choice of a type is made

![image](https://user-images.githubusercontent.com/34163838/35576875-6a018274-05e0-11e8-9702-9ce5ce77284f.png)

**Comment by stempler** [comment]
The behavior at the moment should be that once you select the type it reflects the setting that you chose when importing the file as schema, e.g. if you specified there if the first row contains the headers or not. The assumption is that files with a similar schema (or even the same file) usually all have a header row or not.

Could be that the functionality is not working as intended though.

**Comment by JohannaOtt** [comment]
When importing the file as a schema, I don't see any choice specifying if the first row contains the headers or not. Is that assumed automatically when I use the suggested properties (resulting from the first row) in "Typename Settings"?

**Comment by thorsten-reitz** [comment]
@JohannaOtt Is this fixed through the changes introduced for https://github.com/halestudio/hale/issues/796?

**Comment by JohannaOtt** [comment]
> When importing the file as a schema, I don't see any choice specifying if the first row contains the headers or not.

This is still the case. So I would assume that the logic decribed here

> The behavior at the moment should be that once you select the type it reflects the setting that you chose when importing the file as schema

also still cannot work.
The behavior is different though from what was originally described

> right now the checkbox is checked by default when entering that page of the wizard but is unchecked as soon as a choice of a type is made

It now assumes 0 lines to skip when opening the dialogue and changes it to 1 line to skip when choosing a type.
So from my perspective, the misleading behavior from the description does not occur any longer and the issue could be closed.
@stempler Woud a follow up ticket be needed for the fact that during schema import, there is no option to chose the number of lines to skip?

**Comment by stempler** [comment]
> Woud a follow up ticket be needed for the fact that during schema import, there is no option to chose the number of lines to skip?

I guess that would then be a feature to read the "header row" for the type from something else than the first line?
Not sure if that's a use case. I would not deem it a priority though.
Maybe @thorsten-reitz can comment because he had the "skip multiple lines" use cases.

**Comment by thorsten-reitz** [comment]
Indeed, there is sometimes the use case that the header is not actually in the first line, e.g. in "Hauskoordinaten" or in the AIXM obstacle data that I recently processed. However, there is an easy workaround by just providing a separate schema file. In summary, I would not consider it necessary to specifiy the header line.

**Comment by JohannaOtt** [comment]
> So from my perspective, the misleading behavior from the description does not occur any longer and the issue could be closed.
> 
> In summary, I would not consider it necessary to specifiy the header line.

Given that all points discussed in this ticket are not considered to be valid/needed, the issue is closed now.
