### ISSUE TITLE
Loading a project with multiple sources triggers transformation each time

### ISSUE THREAD

**Issue by stempler** [halestudio/hale#504]
When loading a project that has multiple source data files the transformation and validation are triggered for each file that is loaded, very much slowing down the process of loading the project.

This did not occur in 3.3.1, but now happens in 3.3.2

**Comment by florianesser** [comment]
[This commit](https://github.com/halestudio/hale/pull/462/commits/c2491e1450f1df9a8844e16b76883bf02a8465cf) changes the order execution of the I/O configurations to explicitly load the alignment before the source data. Therefore, [this](https://github.com/halestudio/hale/blob/7a979ca2eba6a42e8b1f4ee4691bed159fb15d75/ui/plugins/eu.esdihumboldt.hale.ui/src/eu/esdihumboldt/hale/ui/service/instance/internal/orient/OrientInstanceService.java#L450) no longer evaulates to false during the project load phase and causes the transformation to be run after every added source.

To prevent his, I suggest that we disable live transformation while a project is loaded.

**Comment by florianesser** [comment]
[Build w/ fix](https://builds.wetransform.to/job/hale/job/hale%7Epublish(master)/331/)
