### ISSUE TITLE
in the importing XML/GML data dialog, set default to "no interpolation"

### ISSUE THREAD

**Issue by JohannaOtt** [halestudio/hale#508]

**Comment by thorsten-reitz** [comment]
The reason why the default is to interpolate data is that if the source data contains arcs, then they can be processed normally by hale studio. Otherwise, if left unprocessed, the only option is to pass-through geometries as they are.

**Comment by stempler** [comment]
@JohannaOtt What would be the reason?

**Comment by JohannaOtt** [comment]
ok, I wasn't sure if the interpolation also effects other geometries than arcs. But it doesn't.
