### ISSUE TITLE
properties describing "Errors" and "Warnings" can't be scrolled with the mouse

### ISSUE THREAD

**Issue by JohannaOtt** [halestudio/hale#509]
"Occurring values" for example can be scrolled with it

**Comment by thorsten-reitz** [comment]
Can you explain that a bit better? In which views does the issue occur?

**Comment by thorsten-reitz** [comment]
Can you extend the issue descriptio? In which views does the issue occur?

**Comment by JohannaOtt** [comment]
I can't scroll in the "Errors"- and in the "Warnings" in the Properties-view with my scroll wheel. It occurs in version 3.3.1 as well as in the 3.4.0 SNAPSHOT (build 331)

**Comment by florianesser** [comment]
@JohannaOtt Can you provide a screenshot of the situation where this happens, please? I can scroll in the list in the Properties view here e.g.:
![grafik](https://user-images.githubusercontent.com/1867607/38078105-7b80ae66-333b-11e8-842d-815090187d2c.png)

**Comment by JohannaOtt** [comment]
![image](https://user-images.githubusercontent.com/34163838/38078726-79699ffa-333d-11e8-852f-e391538905e9.png)

[Build 368] I can scroll clicking on the bar but can't scroll using my mouse wheel.

**Comment by stempler** [comment]
Could be an issue of the embedded component (e.g. list/table/tree viewer) exceeding the size of the properties view, which results in a scroll bar being displayed (sometimes this results on two scroll bars, one in the view, one in the viewer). The mouse scroll event is probably be captured by the viewer.
