### ISSUE TITLE
Unable to connect to hale connect when proxy is required

### ISSUE THREAD

**Issue by stempler** [halestudio/hale#521]
Reported by @JuergenWeichand.

Are maybe the proxy settings not used here?

**Comment by florianesser** [comment]
[Build w/ fix](https://builds.wetransform.to/job/hale/job/hale%7Epublish(master)/360/)

**Comment by thorsten-reitz** [comment]
Who can test this? Did a customer test the build already?

**Comment by stempler** [comment]
@florianesser did some testing with a local proxy, unless we get any further feedback that would be sufficient for me to close the issue.
