### ISSUE TITLE
Export transformed data as shapefiles

### ISSUE THREAD

**Issue by thorsten-reitz** [halestudio/hale#522]
Add the ability to export transformed data as shapefiles, with one shapefile being written per target feature type. To be able to do this, the target schema needs to be flattened and attribute names be shortened to 11 characters. We should only write attributes to the shapefile that are actually used by the data.

I propose the following flattening and shortening approach:

1. To flatten complex attributes, create a full path to the property being filled in, with underscore characters to separate levels. Use numbers to indicate list positions, e.g. like this: `geographicalName_0_GeographicalName_language`
2. If the resulting string is longer than 11 characters, use the following rules to shorten it in a first approach:
    1. Keep only the first letter and any Camecased letters; in other words, if all letters are capitalized, only the first one is kept
    2. Keep all numbers
    3. Keep the last word
3. The example from before should now look like this: `gn0gnlanguage`, with a total of 13 charcters. as such, it is still too long, and the next rule needs to be applied.
4. If the attribute name is still too long, truncate to 11 characters: `gn0gnlangua`. This now matches.
5. as a final check, we need to verify whether any collisions (attributes that have the name shortened name) occur during shortening. If that is the case, the last letter is removed and replaced with a number for each attribute that has the same shortened name.

Some nested attribute structures tend to be very deep (e.g. `CI_Citation`). For those it would make sense to remove a number of middle elements altogether.

**Comment by florianesser** [comment]
duplicates #224, keeping this version

**Comment by florianesser** [comment]
@thorsten-reitz Would you agree that this was implemented (and subsequently enhanced) by [this PR](https://github.com/halestudio/hale/pull/913)?

**Comment by thorsten-reitz** [comment]
Yes, fine with me. Going more in depth would require something like the model trafos.
