### ISSUE TITLE
filtering source data instances takes long

### ISSUE THREAD

**Issue by JohannaOtt** [halestudio/hale#528]
when entering a cql filter on the source data, the source data set is filtered after every letter entered - as there are no results for unfinished filter expressions, it filters all the source data after every letter until the filter query is actually complete. Particularly for bigger datasets, this process takes quite long.
Maybe a button to actually start filtering (once the query is finished) would be helpful? Otherwise maybe a delay of one or two seconds could maybe be an option so the user has the chance to finish his/her query.

**Comment by florianesser** [comment]
[Feature build](https://builds.wetransform.to/job/hale/job/hale%7Epublish(master)/370/)

**Comment by thorsten-reitz** [comment]
LGTM with build 378, tested with a larger data set
