### ISSUE TITLE
Login button in export wizard is hidden

### ISSUE THREAD

**Issue by JohannaOtt** [halestudio/hale#529]
if you want to export a transformation project to hale connect and are not yet logged in, you don't see the login button until you change the size of the wizard.

![image](https://user-images.githubusercontent.com/34163838/36724470-974946ca-1bb3-11e8-8b3c-d28a76e919d9.png)

![image](https://user-images.githubusercontent.com/34163838/36724560-db5467be-1bb3-11e8-8410-432c00a91054.png)

**Comment by florianesser** [comment]
[Build w/ fix](https://builds.wetransform.to/job/hale/job/hale%7Epublish(master)/372/)

**Comment by stempler** [comment]
I still have the same problem. The initial width (and in my case also the height) of the wizard seems to be too small:
![screenshot from 2018-04-04 14-25-42](https://user-images.githubusercontent.com/375475/38307461-20d07f40-3814-11e8-8187-6ecc47b2a754.png)

**Comment by thorsten-reitz** [comment]
LGTM to me now:
![grafik](https://user-images.githubusercontent.com/3470356/38563982-72a7c52a-3cde-11e8-86cd-c9f21aaf50fc.png)
@stempler is there still an issue on Linux?

**Comment by stempler** [comment]
![screenshot from 2018-04-11 11-56-25](https://user-images.githubusercontent.com/375475/38609820-68c1ae1c-3d7f-11e8-99fd-4eb7ab8d0214.png)
Not ideal but at least now all components are visible.
