### ISSUE TITLE
Application is very slow on Linux with GTK ~3.18

### ISSUE THREAD

**Issue by stempler** [halestudio/hale#53]
This is due to a bug in the underlying SWT implementation. The same issue can be observed with Eclipse Mars. In Eclipse Neon the problem seems to be fixed. An update to Eclipse Neon however is not a trivial task for hale, as some UI mechanisms retained from Eclipse 3 seem to be no longer supported.

Workaround is switching to GTK 2 for running hale. This can be done by adapting the `HALE.ini` file.
You need to add the following lines before the `-vmargs` line:

```
--launcher.GTK_Version
2
```

**Comment by milovanderlinden** [comment]
This should also be done if you get I/O wizard errors. Thankfully I came across this tip!

**Comment by thorsten-reitz** [comment]
@milovanderlinden @johanvdw Thanks for the feedback.

@stempler probably we have to check what a migration to a current Eclipse version would mean. I don't see this happening before hale studio 4.0.0 though.

**Comment by johanvdw** [comment]
Thorsten,
I saw this error on  HALE version 3.3.1.

**Comment by thorsten-reitz** [comment]
@stempler @florianesser shouldn't this be fixed with the changes we have made?

**Comment by florianesser** [comment]
@thorsten-reitz Yes, this should no longer be an issue with the upgrade to the Photon platform. @stempler Can you confirm?

**Comment by stempler** [comment]
It is no longer a problem on my machine and I think using the Photon based version also worked for a couple of other people.

**Comment by thorsten-reitz** [comment]
OK, I'll close this then.
