### ISSUE TITLE
disable scientific notation on number values for GML export

### ISSUE THREAD

**Issue by doemming** [halestudio/hale#544]
Although scientific notation is valid according XML specification, often project specific needs require non scientific notation of numbers.
Possible solutions could be 
- adding an option to disable scientific notation on GML export.
- support this feature via groovy based functions, e.g. provide value class that extends from Integer (e.g. FormattedInteger) and overwrite toString() with custom behaviour. This way might allow to use different serialisations on specific attributes. The value call could be used explicit via groovy script to set a target value.

**Comment by stempler** [comment]
@doemming @JohannaOtt Would you please test this for your use case with the [current build](https://builds.wetransform.to/job/hale/job/hale~publish(master)/368/) (once it is done)?

**Comment by stempler** [comment]
Tested by @JohannaOtt
