### ISSUE TITLE
Task icon on cell disappears when it is replaced

### ISSUE THREAD

**Issue by stempler** [halestudio/hale#559]
Even though tasks on a cell are retained when a cell is replaced the icon in the Alignment view is not displayed after the replace. It is displayed again for instance when the project is saved and reloaded.

**Comment by stempler** [comment]
Maybe a similar problem as in the Mapping view before https://github.com/halestudio/hale/commit/516a7adfd18cfbf4a6c7fe6e41c1bcd6cf89230c?

At least testing with the indy-Version I see that updates to the Alignment view often are not done when they should.

**Comment by stempler** [comment]
> At least testing with the indy-Version I see that updates to the Alignment view often are not done when they should.

That behavior could also be related to https://github.com/halestudio/hale/commit/e3d4f1c1886b188e76245be9214c3365ebcbf7d6

**Comment by florianesser** [comment]
[Build w/ fix](https://builds.wetransform.to/job/hale/job/hale%7Epublish(master)/362/)
