### ISSUE TITLE
Choosing "Replace with" for a function cell does not change the Alignment view

### ISSUE THREAD

**Issue by JohannaOtt** [halestudio/hale#562]
Version 3.4.0.SNAPSHOT
Build 15
Revision a659e5d988058ffc2e2dba6fb8e961dd9b7e7151

-chose Replace with for a function
-configure the new function
-press Finish
-the Alignment view is only updated after reloading the FeatureType Mapping
-gives the impression, replacement did not happen

**Comment by stempler** [comment]
I think that is fixed with https://github.com/halestudio/hale/commit/e3d4f1c1886b188e76245be9214c3365ebcbf7d6. Also have this problem in the indy version and it is quite annoying.
