### ISSUE TITLE
Added isolated workspaces support to App-Schema plug-in

### ISSUE THREAD

**Issue by thorsten-reitz** [halestudio/hale#572]
See PR #519 for details.

**Comment by thorsten-reitz** [comment]
@florianesser or @stempler please post the link to the feature build once availabe here.

**Comment by florianesser** [comment]
[Feature build](https://builds.wetransform.to/job/hale/job/hale%7Epublish(master)/366/)

**Comment by stempler** [comment]
I tested this with a current GeoServer version before approving the PR. So from my side could be closed.

**Comment by thorsten-reitz** [comment]
@nmco Do you want to also test with this build?  Otherwise we will close the issue.

**Comment by nmco** [comment]
Tested, this can be closed, thanks @thorsten-reitz !

**Comment by thorsten-reitz** [comment]
thanks @nmco !
