### ISSUE TITLE
HTML documentation: FeatureType name is displayed incorrectly

### ISSUE THREAD

**Issue by JohannaOtt** [halestudio/hale#577]
Version 3.4.0.SNAPSHOT - Build 368 - Revision 75be327b59db683fbe761dc60f436c965667b150

When exporting the alignment as HTML, the names of all FeatureTypes are displayed left from where the cell is displayed:
![image](https://user-images.githubusercontent.com/34163838/38233576-3eb821c4-371b-11e8-96a5-413521e607d0.png)

**Comment by florianesser** [comment]
@JohannaOtt What browser did you use to view that? Does it happen w/ Firefox or Chrome?

**Comment by JohannaOtt** [comment]
I tried with Edge, Chrome, and Firefox. It displayed incorrectly in all of them.

**Comment by florianesser** [comment]
Works fine w/ the Hydrography example. This may be a halejs issue with that particular alignment. Noticeable is the lack of the `infoCircle` in the type figure on the right.

**Comment by florianesser** [comment]
@JohannaOtt Do you happen to remember in which project this happened?

**Comment by JohannaOtt** [comment]
This happened in a Mudab project: e.g. https://wetransform.app.box.com/file/288324705819

**Comment by JohannaOtt** [comment]
As this issue did not occur anymore for some time, I close this issue.
In case it happens again for a specific project one day, a new issue can be created.
