### ISSUE TITLE
transformation after loading schemas and after every loaded data source

### ISSUE THREAD

**Issue by JohannaOtt** [halestudio/hale#583]
Version 3.4.0.SNAPSHOT - Build 373 - Revision ef643ef8ce872213a62b155e5fd0804ddad7b8e2

While opening an existing transformation project, the transformation is triggered after loading the schemas and after loading every single data source. That leads to confusing entries in the log. Transforming the loaded data several times while opening the project may also lead to a longer duration for opening projects with a lot of or big source data sets.

![image](https://user-images.githubusercontent.com/34163838/38351272-127b5e42-38af-11e8-8a37-6e943cd52461.png)

![image](https://user-images.githubusercontent.com/34163838/38351277-1681f708-38af-11e8-97b2-fbcc0bad227c.png)

**Comment by florianesser** [comment]
@JohannaOtt Could you please test this with [this build](https://builds.wetransform.to/job/hale/job/hale%7Epublish(master)/387/) and verify that this doesn't happen anymore?

**Comment by JohannaOtt** [comment]
tested it and it doesn't happen any more.

**Comment by florianesser** [comment]
Thanks, @JohannaOtt!
