### ISSUE TITLE
Application freezes on macOS 10.13 (High Sierra)

### ISSUE THREAD

**Issue by florianesser** [halestudio/hale#584]
When hale studio is started on macOS 10.13, no action can be taken after startup. Both the menu bar and the application window are completely unresponsive.

Possible cause: https://bugs.eclipse.org/bugs/show_bug.cgi?id=520176

**Comment by thorsten-reitz** [comment]
Upgrading to the latest MacOS solves this issue.

**Comment by florianesser** [comment]
Could not be reproduced w/ macOS 10.13.4, closing for now

**Comment by florianesser** [comment]
Reopening based on a user reporting that hale studio freezes on his macOS 10.13.4

**Comment by florianesser** [comment]
The Eclipse platform has been upgraded in the [latest snapshot builds](https://builds.wetransform.to/job/hale/job/hale%7Epublish(master)/). Testing required to see if the upgrade solves this issue.

**Comment by LorenzoStucchi** [comment]
Hi, I test the linked version on my MacBook Pro with macOS High Sierra 10.13.6 and work, I test to open a project done on Windows and it works. Thanks very much

**Comment by florianesser** [comment]
@LorenzoStucchi Thanks a lot for the quick feedback!
