### ISSUE TITLE
unify winding order in EPSG:4258

### ISSUE THREAD

**Issue by JohannaOtt** [halestudio/hale#597]
export GML Feature Collection with "Convert to CRS" activated and chose 4258
set "unify winding order" to "unify winding order to counterclockwise" results in validation error in INSPIRE validator with "[...]The feature geometry is not a valid GML geometry. Error detected: Invalid polygon. Outer ring of polygon is clockwise within element MultiSurface [...]".
Choosing "unify winding order to clockwise" leads to a successful validation.

**Comment by stempler** [comment]
There is also a report that data transformed to EPSG 4258 with hale is displayed incorrectly in QGIS. So there could be a relation if something is amiss with the axis order.

**Comment by florianesser** [comment]
@stempler This is most likely a QGIS problem. The axis order of EPSG:4258 is [defined](http://epsg-registry.org/export.htm?wkt=urn:ogc:def:crs:EPSG::4258) as lat/lon. QGIS uses a lon/lat axis order for 4258 instead (screenshot is from QGIS 3.0.0).

![2018_04_17_14_23_44_koordinatenbezugssystem_auswahl](https://user-images.githubusercontent.com/1867607/38869493-268d2398-424b-11e8-9f72-8212f4f53708.png)

**Comment by florianesser** [comment]
@JohannaOtt It's possible that ran into [this bug](https://github.com/inspire-eu-validation/ets-repository/issues/137) of the INSPIRE validator.

**Comment by stempler** [comment]
> @JohannaOtt It's possible that you ran into this bug of the INSPIRE validator

Seems very likely. AFAIK the algorithm in hale that checks the winding order takes the CRS axis order into account.
Thanks @florianesser

**Comment by Kate-Lyndegaard** [comment]
Hi,
It looks like QGIS is using the Proj4 file from the EPSG database on spatialreference.org to identify EPSG:4258. You can see the Proj4 file for EPSG:4258 here: http://www.spatialreference.org/ref/epsg/4258/proj4/

@KateLyndegaard
