### ISSUE TITLE
When partitioning by feature type, GML file names always start with "gml."

### ISSUE THREAD

**Issue by florianesser** [halestudio/hale#609]
In case compression is not used, i.e. the selected target file is e.g. `output.gml`, the partitioned output files will always be called `gml.<FeatureType>.gml`.

**Comment by thorsten-reitz** [comment]
I can confirm this behaviour. There is no build for this yet, right?

**Comment by florianesser** [comment]
Sorry, forgot to link the build: [here it is](https://builds.wetransform.to/job/hale/job/hale%7Epublish(master)/396/)

**Comment by thorsten-reitz** [comment]
LGTM
