### ISSUE TITLE
Basic support for custom transformation functions

### ISSUE THREAD

**Issue by stempler** [halestudio/hale#61]
Allow the user to define custom reusable transformation functions. First implementation is based on defining Groovy scripts. Custom functions can be stored in the alignment or included from an external source (later).

**Comment by stempler** [comment]
TODOs:
- Improve mapping on schema elements, support mapping anonymous types
- Improve entity settings page
- Add UI for specifying parameters

**Comment by thorsten-reitz** [comment]
Potential improvement:

* Indicate which source/target properties/elements are affected by the custom function

**Comment by thorsten-reitz** [comment]
Priorities for release 3.0.0:

* Documentation in hale help

The other aspects are to be part of the next release.
