### ISSUE TITLE
"Isolated" check box cannot be selected in App-Schema alignment export

### ISSUE THREAD

**Issue by florianesser** [halestudio/hale#611]
In the App-Schema export wizard on the `Configure workspaces` page, the checkbox in the `Isolated` column cannot be activated.

**Comment by florianesser** [comment]
The GTK3 issues look like to have been fixed w/ the Photon platform upgrade. Since this won't be part of the bugfix release, I'm moving this ticket back to the 3.5.0 milestone.

**Comment by thorsten-reitz** [comment]
LGTM
