### ISSUE TITLE
Partition Output by spatial extent

### ISSUE THREAD

**Issue by thorsten-reitz** [halestudio/hale#614]
As a user, I want to partition the exported transformed data by its spatial extent.

Suggested approaches:

* Dataset bounding box quadtree scheme
* WGS84 Tile level quadtree scheme
* Projected Coordinate Reference System Quadtree scheme

At least one of these schemes should be implemented. The user should be able to pick the subdivision  level. Filenames of generated files should contain the treekey in the selected quadtree grid.

As each object may intersect multiple tile BBoxes, but shall be include din only one, I suggest to use the centroid of the object to determine to which tile it will be written.

**Comment by florianesser** [comment]
[Feature build](https://builds.wetransform.to/job/hale/job/hale%7Epublish(master)/406/)

**Comment by thorsten-reitz** [comment]
@florianesser that link doesn't work - is any of the newer builds also fine?

**Comment by florianesser** [comment]
@thorsten-reitz Yes, you can use any of the newer builds! We recently reduced the number of builds that Jenkins keeps, so it might happen more often in the future that the specific feature build has already been deleted. It's not a problem to use a later build, though.

**Comment by thorsten-reitz** [comment]
LGTM
