### ISSUE TITLE
Add AAA schema (6.0.1) as cached resource

### ISSUE THREAD

**Issue by stempler** [halestudio/hale#615]
When using the schema preset introduced in https://github.com/halestudio/hale/pull/527 it seems from time to time (e.g. Feb 27th 2018, May 14th 2018) the server is not available:

```
$ ping repository.gdi-de.org
ping: unknown host repository.gdi-de.org
```

Adding the schema to the cached resources would allow the schema to be loaded also in this case.
The main part of the implementation (building the bundle) would need to be done in [hale-platform](https://github.com/halestudio/hale-platform)

**Comment by thorsten-reitz** [comment]
LGTM
