### ISSUE TITLE
extend help for Merge function

### ISSUE THREAD

**Issue by JohannaOtt** [halestudio/hale#617]
The parameter descriptions concerning the Merge function in the hale studio help (http://help.halestudio.org/latest/topic/eu.esdihumboldt.cst.doc.functions/functions/eu.esdihumboldt.hale.align.merge.html?cp=0_6_3_0_6) only provide limited information on how they are influencing the effect of the function. An example for each of the parameters and how they change the functions output would be helpful.
This might also be the case for other (complex) functions.

**Comment by thorsten-reitz** [comment]
@JohannaOtt would you or @Kate-Lyndegaard be able to create a patch for that?

**Comment by Kate-Lyndegaard** [comment]
Hi @thorsten-reitz,
I am collecting a list of these types of issues in ING-2132, but yes, I can add some more documentation. Regular joins, spatial joins, assign bound, classification, aggregate, loading multiple WFS, getting pro plugins are all lacking documentation.

Regarding the Merge function, I know that I expected to be able to merge more than 1 source dataset, as that is standard in GIS. That is an extension that would require development, however.

**Comment by JohannaOtt** [comment]
@thorsten-reitz I will clarify with @Kate-Lyndegaard on this as well as #807 and #637 as she already started there (as mentioned above) and I don't want to create any mess.
Then I will clarify with @florianesser how we can contribute here.

**Comment by JohannaOtt** [comment]
Is now covered by #816
