### ISSUE TITLE
LineStrings in gml file with CompoundCRS are misread

### ISSUE THREAD

**Issue by JohannaOtt** [halestudio/hale#627]
when importing the attached gml source file (srsName="urn:adv:crs:ETRS89_UTM32*DE_DHHN2016_NH") in hs with EPSG:25832, LineStrings in terrainIntersection are misread (displaying in a triangle Germany - Somalia - Nigeria) while LinearRings in MultiSurface display fine. The srsDimension is defined in the posList element for both.
When exporting the file with EPSG:4258 the geometries of LineStrings with an even number of ordinate triples get completely confused (see attached gml output file). The srsDimension is defined in the MultiCurve/MultiSurface element.
An assumption for that behaviour is that LineStrings with an even number of ordinates are interpreted as 2D geometries and therefore confused.

[3DissueExample.zip](https://github.com/halestudio/hale/files/2101431/3DissueExample.zip)

**Comment by stempler** [comment]
The description hints on that the srsDimension might not be interpreted correctly, maybe because it is provided on level of the `posList`.

**Comment by florianesser** [comment]
@JohannaOtt Could you please test this fix? You can use build [426](https://builds.wetransform.to/job/hale/job/hale%7Epublish(master)/426/).

**Comment by JohannaOtt** [comment]
looks good
