### ISSUE TITLE
Cannot build HALE 3.4.0 release

### ISSUE THREAD

**Issue by nmco** [halestudio/hale#629]
Build of HALE 3.4.0 release (from 3.4.0 TAG):
```
commit 5a1b7c06877a03c634c85979a9ae0499535085cc
Author: Florian Esser <fe@wetransform.to>
Date:   2018-04-23 13:34:10
Set version for 3.4.0 release
```

Tries to resolve the following dependency and fails to do it:
```
eu.esdihumboldt:eu.esdihumboldt.hale.io.feature.deegree:3.5.0.SNAPSHOT
```

This dependency looks a bit suspicious to me ... anyway, is there any particular step I need to take to build this release ?

**Comment by florianesser** [comment]
I successfully built from the `3.4.0` tag w/ a clean checkout and a clean build environment (`rm -rf ~/.m2/repository; rm -rf ~/.gradle`). So I suspect the problem you are facing is somehow related to your build environment, @nmco.

**Comment by thorsten-reitz** [comment]
@nmco can this ticket be closed?

**Comment by nmco** [comment]
I'm still not able to build it, but this is not a concern anymore since the HALE 3.4.0 binaries have been fixed. So, yes it cna be closed. Thank you for the help @thorsten-reitz  and @florianesser.

**Comment by thorsten-reitz** [comment]
Thanks for the feedback @nmco!
