### ISSUE TITLE
exporting alignment as hale connect project leads to change of lookup table paths

### ISSUE THREAD

**Issue by JohannaOtt** [halestudio/hale#642]
Version 3.5.0.SNAPSHOT
Build 409
Revision c75b54928ec8c93b98f491069377135e74512bdd

-project with local paths for lookup tables
-export to hc as hale connect project
-paths of lookup tables change to C:/Users/[...]/AppData/Local/Temp[...]

**Comment by JohannaOtt** [comment]
And it seems as it is also loosing its source data paths

**Comment by florianesser** [comment]
@JohannaOtt Could you please test this with [this build](https://builds.wetransform.to/job/hale/job/hale%7Epublish(master)/449/)?

**Comment by JohannaOtt** [comment]
I think the error is fixed but there is still an issue with the paths displayed
before uploading the project to hale connect:
![grafik](https://user-images.githubusercontent.com/34163838/50769276-c2385c00-1283-11e9-9174-e3784aaddd46.png)
after uploading the project to hale connect:
![grafik](https://user-images.githubusercontent.com/34163838/50769590-b600ce80-1284-11e9-98b3-66b38b890b17.png)

The paths shown in the Project view, where the little arrows have been "extended" before uploading the project remain the local ones as expected, all the others still change to paths in the AppData-Folder. When closing and reopening the Project view, they all show the expected local paths again. Also, the halex-file does not change.
That is why I assume that there is only a displaying error in the Project view left.

**Comment by JohannaOtt** [comment]
LGTM
