### ISSUE TITLE
loaded data is transformed after every source loaded when changing the feature sampling

### ISSUE THREAD

**Issue by JohannaOtt** [halestudio/hale#644]
Version 3.5.0.SNAPSHOT
Build 409
Revision c75b54928ec8c93b98f491069377135e74512bdd

same behaviour as in https://github.com/halestudio/hale/issues/583. In 583, loading the transformation project was concerned. The behaviour now only occurs when updating the number of the feature sampling.

**Comment by florianesser** [comment]
Feature build: [412](https://builds.wetransform.to/job/hale/job/hale%7Epublish(master)/412/) or later
