### ISSUE TITLE
value of EncodedValuesPropertyType is not written in GML output

### ISSUE THREAD

**Issue by JohannaOtt** [halestudio/hale#645]
Version 3.5.0.SNAPSHOT
Build 409
Revision c75b54928ec8c93b98f491069377135e74512bdd

the Observation-part of INSPIRE Soil contains an element with the type EncodedValuesPropertyType (from http://schemas.opengis.net/sweCommon/2.0/basic_types.xsd#0:0). When filling it with values, hs shows the error "Value provided for target that does not allow a value according to the schema" and does not write the value when exporting the GML even though it should be possible.

**Comment by stempler** [comment]
We need to check if the assumption here then is not correct:
https://github.com/halestudio/hale/blob/b0a86be87afc9b08a7a1194b35dca715b88927dc/io/plugins/eu.esdihumboldt.hale.io.xsd/src/eu/esdihumboldt/hale/io/xsd/reader/XmlSchemaReader.java#L1504

**Comment by florianesser** [comment]
As far as I understand the XML spec, the type `anyType` allows arbitrary content and a type _extending_ (not restricting) `anyType` also allows arbitrary content, regardless of the `mixed` flag (see also [this StackExchange thread](https://stackoverflow.com/questions/29455790/does-a-complex-extending-xsanytype-allow-textual-content)).

Therefore, I think the `XmlSchemaReader` should enable the `HasValueFlag` in cases where the extended type is `anyType` (like in the example provided by @JohannaOtt and for `TypeA` in the example below).

Additionally, I think the `HasValueFlag` needs also to be enabled in cases where the type hierarchy can be traced back to an `anyType` extension, like in this example for `TypeB` (but I guess this is harder to implement):

```
<!-- Both types allow arbitrary content and require mandatoryAttribute to be present -->

<complexType name="TypeA">
	<complexContent>
		<extension base="anyType">
			<attribute name="optionalAttribute" type="string"/>
			<attribute name="mandatoryAttribute" use="required" type="string"/>
		</extension>
	</complexContent>
</complexType>

<complexType name="TypeB">
	<complexContent>
		<extension base="tns:TypeA" />
	</complexContent>
</complexType>
```

**Comment by stempler** [comment]
Thanks @florianesser !
The thread you linked to is helpful, but brings up another question for me. Is the handling of mixed types regarding inheritance then also generally wrong? We assume that mixed is not inherited. If that's not correct, the question is there something stops being mixed (as everything goes back to anyType at some point).

We had at some points problems when anything could have a value because it inherited from anyType. Then we made the `HasValueFlag` in anyType not inheritable.

**Comment by florianesser** [comment]
> We assume that mixed is not inherited. If that's not correct, the question is there something stops being mixed (as everything goes back to anyType at some point).

The [XML spec](https://www.w3.org/TR/xmlschema-1/) says that in case of an `extension` the extending and the extended type must either both be `mixed` or both be `element-only`:
```
1.4.3.2.2.1 Both {content type}s must be mixed or both must be element-only.
```
In general, any type extending a `mixed` type must, therefore, explicity set `mixed="true"` itself. I have found one exception to this rule, though: If the extending type only adds attributes, then it does need to define `mixed="true"` and even if it explicitly sets `mixed="false"` that setting is ignored and the type is `mixed` nonetheless.

```
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.example.org/NewXMLSchema" xmlns:tns="http://www.example.org/NewXMLSchema" elementFormDefault="qualified">
	<complexType name="A">
		<complexContent>
			<extension base="anyType">
				<attribute name="test" use="required"/>
			</extension>
		</complexContent>
	</complexType>
	
	<complexType name="B">
		<complexContent mixed="false"> <!-- this mixed="false" is ignored, the type is mixed -->
			<extension base="tns:A">
				<attribute name="test2" use="required"></attribute>
			</extension>
		</complexContent>
	</complexType>

	<complexType name="C">
		<complexContent> <!-- this type is mixed, although mixed="true" is not specified -->
			<extension base="tns:A">
				<attribute name="test3" use="required"></attribute>
			</extension>
		</complexContent>
	</complexType>
	
	<element name="b" type="tns:B"/>
</schema>
```
The following document validates against this schema:
```
<?xml version="1.0" encoding="UTF-8"?>
<tns:b xmlns:tns="http://www.example.org/NewXMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" test="bcd" test2="abc">fdfsd<hjf></hjf>fhdjfhsdjkfds</tns:b>
```

> We had at some points problems when anything could have a value because it inherited from anyType. Then we made the HasValueFlag in anyType not inheritable.

My understanding is that if the type is an `extension` of `anyType` (`<complexContent><extension base="anyType">`) or of another type that is an `extension` of `anyType` it would also need to get the `HasValueFlag` (b/c it must be `mixed`), but not if it is a `restriction` of `anyType` (`<complexContent><restriction base="anyType">`). Typical types will have a `restriction` on `anyType` somewhere along the type hierarchy, e.g. this definition
```
<xs:complexType name="length3">
 <xs:sequence>
  <xs:element name="size" type="xs:nonNegativeInteger"/>
  <xs:element name="unit" type="xs:NMTOKEN"/>
 </xs:sequence>
</xs:complexType>
```
is just a shorthand version of
```
<xs:complexType name="length2">
 <xs:complexContent>
  <xs:restriction base="xs:anyType">
   <xs:sequence>
    <xs:element name="size" type="xs:nonNegativeInteger"/>
    <xs:element name="unit" type="xs:NMTOKEN"/>
   </xs:sequence>
  </xs:restriction>
 </xs:complexContent>
</xs:complexType>
```
and both `length3` and `length2` should not inherit `HasValueFlag`.

**Comment by stempler** [comment]
Thanks for the research! Probably we need to revisit that then in case real support for mixed types is added.

**Comment by stempler** [comment]
@JohannaOtt Please close the issue once you verified that it works for you with the current build.

**Comment by JohannaOtt** [comment]
The error does not occur anymore and I have values for "values" in the output GML file.
