### ISSUE TITLE
adapt UI assistance for Groovy Merge

### ISSUE THREAD

**Issue by JohannaOtt** [halestudio/hale#654]
Version 3.5.0.SNAPSHOT
Build 414
Revision 1408e35963e7840002f830c0024b9a2ff26a23c9

When choosing a source attribute in the UI assistance of the  Groovy Merge function the way to access the data is described with "def value = _source.p.xxx.value()". As it is a Merge, there can be several source objects that need to be accessed, so it should be "def value = source.p.xxx.values()".

**Comment by thorsten-reitz** [comment]
@Flaminietta This might also be s suitable mango for you to work on :)

**Comment by Flaminietta** [comment]
Closed with PR #980
