### ISSUE TITLE
Support SSL connection to PostgreSQL/PostGIS

### ISSUE THREAD

**Issue by bstroebl** [halestudio/hale#67]
Our central PostgreSQL/PostGIS server requires users to connect using ssl. When trying to connect to it from Hale I receive this error:
`org.postgresql.util.PSQLException: FATAL: no pg_hba.conf entry for host "hostip", user "username", database "dbname", SSL off`
When entering the credentials there should be a choice of how to connect to the db. In e.g. QGIS these are the choices for SSL:
- disable
- allow
- prefer
- require

maybe disable and require are sufficient, could then be done with a checkbox `connect using SSL` defrault would be no

**Comment by stempler** [comment]
hale uses JDBC to connect to PostgreSQL. A quick search showed me that it seems to be necessary to use a specific JDBC URI to use the PostgreSQL JDBC driver with a SSL connection:

```
jdbc:postgresql://myserver.com:5432/mydatabasename?ssl=true
```

You can enter the JDBC URI in hale when using the **From URL** tab on import. Can you try using a URI like the above including `?ssl=true` and see if you can connect?

If you still can't connect then this might be an issue with the SSL certificate validation. The [PostgreSQL JDBC driver documentation](https://jdbc.postgresql.org/documentation/94/ssl-client.html) provides some hints on that.

**Comment by bstroebl** [comment]
that worked out:

`jdbc:postgresql://myserver:5432/dbname?ssl=true&sslfactory=org.postgresql.ssl.NonValidatingFactory`

As this is an internal server we do not issue an official certificate, hence the none-validating connection.

I am doing my first steps in hale and thus was not aware of the possibility to directly enter a jdbc connection string in the URL tab, otherwise I might have found it myself as I already knew this jdbc expression can connect to our database.

Please close this ticket if you are not going to implement anything in the PostgreSQL/PostGIS tab.

**Comment by stempler** [comment]
Glad to hear that you got it working! Thanks for the feedback.

As there is an easy workaround I don't think we will extend the UI in that way in the near future. One reason is that different databases than PostgreSQL can also be configured through that form - and they probably have different parameters, so this would have to be something that is provided as an extension for PostgreSQL only (which first requires creating such an extension point).
