### ISSUE TITLE
cardinality of gml:id , xsd-resource used for gml 3.2. 

### ISSUE THREAD

**Issue by doemming** [halestudio/hale#674]
I wonder that in HaleStudio's Schema-Explorer "gml:id" is marked in as "required" attribute, but in the corresponding Gml-XSD it is defined as optional. 
see also: http://schemas.opengis.net/gml/3.2.1/gmlBase.xsd

note: The refered xsd-content suggests to be version "3.2.1" by URL, but it describes with a version="3.2.2" attribute in the root element. It looks like a bugfix version "3.2.2" has overwritten the previous "3.2.1" and this results in version "3.2.1" not to be published anymore in the repository :-( . 
Has "gml:id" been set to "required" in "3.2.1" ?

So which version is Hale-Studio currently using for namespace "http://www.opengis.net/gml/3.2" ?

**Comment by doemming** [comment]
I just checked: gml:id has been changed from "required" (3.2.1) to "optional" (3.2.2) in the corresponding xsd-files.

**Comment by thorsten-reitz** [comment]
LGTM
