### ISSUE TITLE
loading FGDB does not work when using GDAL plugin in dropins folder

### ISSUE THREAD

**Issue by JohannaOtt** [halestudio/hale#678]
SNAPSHOT 3.5.0 - Build 427

When trying to import a FGDB as source schema, FGDB-files cannot by chosen (do not get displayed as supported files).

When adding the plugin to the target platform and running hale from Eclipse, it works, though.

**Comment by florianesser** [comment]
This looks like a more general plugin loading issue and will be covered in #696.
