### ISSUE TITLE
GeoJSON export configuration wizard page doesn't appear

### ISSUE THREAD

**Issue by thorsten-reitz** [halestudio/hale#680]
... and geometry gets written to the wrong place. Furthermore, reprojection is not possible.

**Comment by nmtoken** [comment]
Not sure what the comment reprojection is not possible means, but surely for GeoJSON that's expected behaviour? I mean GeoJSON only supports one projection

**Comment by thorsten-reitz** [comment]
GeoJSON by default uses WGS84, but source data may use any spatial reference system, so the data still needs to be reprojected.

In GeoJSON there is also a mechanism to declare that a Geometry uses a specific different CRS, though I think most software doesn't support that:

http://wiki.geojson.org/GeoJSON_draft_version_6#Specification (Point 4)

**Comment by stempler** [comment]
> In GeoJSON there is also a mechanism to declare that a Geometry uses a specific different CRS, though I think most software doesn't support that.

They decided to keep it simple and for the [actual standard](https://tools.ietf.org/html/rfc7946) that was removed - so the CRS of the GeoJson geometry is always expected to be WGS84 with lon/lat, though there is still the possibility to transport geometries in addition in a custom manner, in a property or a foreign member.

That being said, I don't think that the current implementation hale cares for that and just produces the geometries in their original CRS.

**Comment by thorsten-reitz** [comment]
Workaround for the geometry CRS issue: Use a Reproject Geometry function or a groovy function in which a reprojection is done.

**Comment by thorsten-reitz** [comment]
@stempler we discussed yesterday that you'll check whether the existing configuration page should be displayed. By default, data should be reprojected to WGS84, or we need to use the workaround mentioned above.
