### ISSUE TITLE
AppSchema alignment export keeps lock on exported file

### ISSUE THREAD

**Issue by AndyLicht** [halestudio/hale#681]
Hi,
leider können Schemadateien, die gerade exportiert worden sind, nicht über WinSCP auf einen Server kopiert werden. Dies ist erst möglich, wenn Hale geschlossen wird. Kein schwerwiegender Fehler, stört aber dennoch den Arbeitsprozess.

beste Grüße
Tim

**Comment by thorsten-reitz** [comment]
Thanks for your report. To clarify, you exported a hale schema file, and hale kept a lock on that file afterwards?

**Comment by AndyLicht** [comment]
![exportfromhale](https://user-images.githubusercontent.com/9767949/45291233-dc3e7980-b4f1-11e8-8b0f-3bd6948e64ba.PNG)
I export as a App-Schema Configuration.

**Comment by florianesser** [comment]
I can confirm that the AppSchema alignment export appears to keep a lock on exported schema configuration files. However, copying the exported files is possible for me, but they can't be moved/deleted. 

@AndyLicht As a workaround you could try to copy the exported configuration to another directory locally first, before SCP'ing.

**Comment by stempler** [comment]
The plugin for AppSchema was removed from the hale studio code base (see #690), thus I close this ticket.

@ridethepenguin Is there some place we can point user's to regarding where to find the plugin and  where to file bug reports or questions?

**Comment by ridethepenguin** [comment]
@stempler I believe you can attach issues to this GitHub repo:
https://github.com/geosolutions-it/hale-appschema-plugin
