### ISSUE TITLE
Ensure spatial index is always available in CLI transformations

### ISSUE THREAD

**Issue by florianesser** [halestudio/hale#687]
Because currently the creation of the internal source object database is bypassed in cases where the alignment contains only (Groovy) Retype or (Groovy) Create functions, the spatial index will not be built in these cases and transformations will behave differently whether run from hale studio or via the CLI.

A simple fix would be to not bypass database creation for alignments that contain Groovy scripts.

**Comment by JohannaOtt** [comment]
solution from Simon posted in related Slack conversation: "Another option would be changing the default behavior I guess (be it in hale or only in hc), to for instance use the database in case there is any Groovy script based function."
This is the related PR: https://github.com/halestudio/hale/pull/688
I tested it with this dataset https://haleconnect.com/#/dataset/org/163/bde2c511-8398-4b53-9e46-2e3ce7168f88/derivedData and this transformation project https://haleconnect.com/#/dataset/org/163/bde2c511-8398-4b53-9e46-2e3ce7168f88/derivedData and it works.
