### ISSUE TITLE
errors in Schematron validation don't get displayed

### ISSUE THREAD

**Issue by JohannaOtt** [halestudio/hale#692]
Version 3.5.0.SNAPSHOT
Build 419

export transformed data
validate it with Schematron (getting errors)
double click on "Schematron validation" in Report List
errors in the Properties don't get displayed: 
![image](https://user-images.githubusercontent.com/34163838/46606797-dc389600-cafe-11e8-874c-f97143c43cc8.png)

**Comment by JohannaOtt** [comment]
I am currently not aware of any users still using schematron validation. I would therefore vote to close this issue.
@florianesser @stempler Any objections?

**Comment by florianesser** [comment]
I'd be ok with closing it. Can always be reopened in case this affects a user in the future.
