### ISSUE TITLE
Plugins in dropins folder not loaded in hale Photon

### ISSUE THREAD

**Issue by florianesser** [halestudio/hale#696]
The Oracle and FGDB plugins are not loaded with the latest `3.5.0-SNAPSHOT` build based on Eclipse Photon. There is no error message in the Error Log.

**Comment by florianesser** [comment]
Doesn't appear to be a problem with dropins in general as the Oracle driver bundles are available.

**Comment by JohannaOtt** [comment]
workaround is to add "-console" to the hale.ini and enter the commands
-install file:/C:/[...]/hale-studio-3.5.0.SNAPSHOT-win32.win32.x86_64/dropins/to.wetransform.hale.io.oracle_1.4.0/eclipse/plugins/eu.esdihumboldt.hale.io.jdbc.oracle_1.4.0.jar
-ss oracle
-start [numberOfPlugin]
in the console that now opens when starting hale studio

**Comment by thorsten-reitz** [comment]
@florianesser is this still relevant? I haven't used the dropins mechanism in a while.

**Comment by florianesser** [comment]
@thorsten-reitz No, I don't think so. Plugin installation via hale's `Install New Software...` mechanism works fine as is the only installation method we suggest nowadays.
