### ISSUE TITLE
Source data not loaded from relations not being in public schema

### ISSUE THREAD

**Issue by bstroebl** [halestudio/hale#70]
Next problem :-)
I have a couple hundred relations in my PostgreSQL database. They are stored in some 40 database schemas. I can load the relations allright but when loading the data, hale only loads data from relations located in the "public" schema.
By the way I use upper and lower case schema and table names (but that is not the cause as data from relations with all lower case schema and relation names are not loaded either).
Extending the search path with `alter role "myrole" set search_path to public, "myOtherSchema"` doesn't help either.

**Comment by stempler** [comment]
hale will only load data for types/tables that you have in you "Mapping relevant source types", i.e. the types that are displayed in the UI for the source schema. So usually it is best to reduce the types to the tables that you actually need for the mapping.

If you did not reduce the types to the public schema then I don't have a clue on what could go wrong here. Data is retrieved using simple queries à la `SELECT * FROM "schema"."table"` (see [here](https://github.com/halestudio/hale/blob/master/io/plugins/eu.esdihumboldt.hale.io.jdbc/src/eu/esdihumboldt/hale/io/jdbc/JDBCTableCollection.java#L147) and [here](https://github.com/halestudio/hale/blob/master/io/plugins/eu.esdihumboldt.hale.io.jdbc/src/eu/esdihumboldt/hale/io/jdbc/constraints/DatabaseTable.java#L95)). Table and schema names are used in the exact same way they are retrieved from the database (and shown in hale; the schema name is part of the namespace). All source types classified as mapping relevant result in a query to the database (see [here](https://github.com/halestudio/hale/blob/master/io/plugins/eu.esdihumboldt.hale.io.jdbc/src/eu/esdihumboldt/hale/io/jdbc/JDBCInstanceReader.java#L116)).

Do you see any errors or warnings in the **Error Log** view that could account for your problem?

**Comment by bstroebl** [comment]
Hi Simon,
thanks for looking into this. 
Arrrg, I malconfigured the jdbc connection for the source data (it pointed to a different database than the source schema). So it was my fault, sorry for the noise.
