### ISSUE TITLE
When partitioning by feature type in 3.4.1, GML file names always start with "gml."

### ISSUE THREAD

**Issue by Kate-Lyndegaard** [halestudio/hale#701]
This behaviour was reported in issue #609. I am experiencing it again in the 3.4.1 release. The file name I provide upon export is overwritten with 'gml'.

**Comment by florianesser** [comment]
Thanks for reporting this, @Kate-Lyndegaard! It looks as if the fix for this problem was not cherry-picked for the 3.4.1 release. Can you confirm that it works in the latest 3.5.0 snapshot?

**Comment by Kate-Lyndegaard** [comment]
Hi Florian,
Yes, it works great in 3.5.0. I just double-checked.
