### ISSUE TITLE
Update codelist presets in 3.4.1

### ISSUE THREAD

**Issue by Kate-Lyndegaard** [halestudio/hale#703]
I am creating SLD test data for the Production and Industrial Facilities theme. The symbology is based on the following codelist: http://inspire.ec.europa.eu/codelist/ActivityCodeValue:4
This codelist has apparently undergone some changes.
The previous versions had no values, however the latest version contains values. The values do not appear in hale studio after loading the codelist from the presets.

**Comment by stempler** [comment]
hale should actually only load the internal versions in case it cannot be loaded from the registry.

Could you try resetting or disabling the HTTP cache in hale studio and see if that makes a difference?

**Comment by Kate-Lyndegaard** [comment]
I navigated to "Einstellungen" and deactivated the web caching, but it didn't fix it.

**Comment by stempler** [comment]
> I navigated to "Einstellungen" and deactivated the web caching, but it didn't fix it.

Just to be sure, did you reload the project afterwards?

**Comment by Kate-Lyndegaard** [comment]
I actually saved it, closed it and re-opened it.

**Comment by stempler** [comment]
Ok thanks, so we need to check that behavior in general.

**Comment by florianesser** [comment]
@Kate-Lyndegaard The `ActivityCodeValue` code list does not contain any values but only references to other code lists (child concepts). You can see also see that in the [XML representation](http://inspire.ec.europa.eu/codelist/ActivityCodeValue/ActivityCodeValue.en.xml) of the list when looking at the `containeditems` elements: it has only `codelist` children (no `value`s).
