### ISSUE TITLE
Hale studio generates incorrect DescribeFeature type request based on WFS GetCapabilities URL

### ISSUE THREAD

**Issue by Kate-Lyndegaard** [halestudio/hale#704]

**Comment by Kate-Lyndegaard** [comment]
When I enter this GetCapabilities request in hale studio, it adds a colon to the DescribeFeature request that gets generated:

GetCapabilities (no colon after .nl): http://geodata.nationaalgeoregister.nl/kaderrichtlijnwater/wfs?SERVICE=WFS&version=2.0.0&request=GetCapabilities

Hale studio generated DescribeCapabilities (adds colon after .nl):
http://geodata.nationaalgeoregister.nl:/kaderrichtlijnwater/wfs?language=dut&SERVICE=WFS&VERSION=2.0.0&REQUEST=DescribeFeatureType

The presence of this colon makes this DescribeFeature type request fail in hale connect and Florian confirmed that this is a bug in hale studio

**Comment by stempler** [comment]
If you look at what the server returns for the `GetCapabilities` request you can see that it returns the URL like this, with a colon:

```xml
<ows:Operation name="DescribeFeatureType">
  <ows:DCP>
    <ows:HTTP>
      <ows:Get xlink:type="simple" xlink:href="http://geodata.nationaalgeoregister.nl:/kaderrichtlijnwater/wfs?language=dut&"/>
      <ows:Post xlink:type="simple" xlink:href="http://geodata.nationaalgeoregister.nl:/kaderrichtlijnwater/wfs?language=dut&"/>
    </ows:HTTP>
  </ows:DCP>
...
</ows:Operation>
```

So I would say that's a problem with the service returning invalid URLs.

**Comment by florianesser** [comment]
Thanks for the analysis, @stempler!

**Comment by Kate-Lyndegaard** [comment]
Thank you, Simon!
