### ISSUE TITLE
Add information on how to install get the GeoServer AppSchema plugin

### ISSUE THREAD

**Issue by stempler** [halestudio/hale#715]
To inform users how they can install the GeoServer AppSchema plugin we should add at least minimal information on where to find it.

This can be done by including the respective update site in the `HALE.p2.inf` file (see https://github.com/halestudio/hale/pull/691#issuecomment-445372151) and/or by adding a hint to the help.

**Comment by florianesser** [comment]
Can be tested w/ [build 447](https://builds.wetransform.to/job/hale/job/hale~publish(master)/447/) or later

**Comment by thorsten-reitz** [comment]
LGTM.
