### ISSUE TITLE
Support pro plugin installation via update site

### ISSUE THREAD

**Issue by florianesser** [halestudio/hale#719]
Implement as a mitigation for #696.

- [x] Create pro plugins update site project
- [x] Make update site available via `halestudio.org` or `wetransform.to` URL
- ~~Add update site as default~~

**Comment by florianesser** [comment]
I'd suggest to create an update site per hale studio release that contains the plugins compatible with the respective release (similar to what the Eclipse project does), e.g. something like:

- http://download.halestudio.org/pro-plugins/3.4.1
- http://download.halestudio.org/pro-plugins/3.5.0
- etc.

**Comment by florianesser** [comment]
A simple docker image serving the plugins for hale studio 3.4.0/3.4.1 is available at `wetransform/hale-pro-updatesite:3.4.0` (private repo).

**Comment by thorsten-reitz** [comment]
@florianesser I understand reading the comment in https://github.com/halestudio/hale/issues/235 that there is an update site available?

**Comment by JohannaOtt** [comment]
LGTM

I tested installing the plugins from http://build-artifacts.wetransform.to/p2/hale-pro/3.5.0-SNAPSHOT and could load data from a FGDB as well as data from an Oracle DB
