### ISSUE TITLE
Update of property relation to use super type fails

### ISSUE THREAD

**Issue by stempler** [halestudio/hale#72]
Steps to reproduce:
- Create a relation on a property of a type that is present also in a super type
- Change the relation (edit) to use the property in the super type instead
- Relation still points to the property of the sub-type

Workaround:
- Clear the type / cell selection when editing the cell, then select the super type and property

**Comment by arunverma87** [comment]
Not able to reproduce this, but will get back to this bug if in future it happens again.

**Comment by stempler** [comment]
Reevaluate for 3.2.0, close if there is no reproduction case by then.

**Comment by stempler** [comment]
Problem still occurs. Example case was:

- Property mapping exists on a property of a super type
- Edit the cell and select a sub-type for the source, then the same property in that type

A similar change to the target worked, so it seems to reproduce it certain conditions must be met.

**Comment by florianesser** [comment]
[Build containing fix](https://builds.wetransform.to/job/hale/job/hale%7Epublish(master)/250/)
