### ISSUE TITLE
JDBC import, warning: 'Could not determine SRS information for SRID 0'

### ISSUE THREAD

**Issue by dollarklavs** [halestudio/hale#733]
I get a warning when importing data from a postgres table:
   _'Could not determine SRS information for SRID 0'_.
the tables that I import both have well defined geoemtries. 

```
CREATE TABLE raastofomraader.mst_inspire_am1
(
  gmlid character varying(62),
  inspireid_lokalid numeric(38,0),
  inspireid_namespace character(61),
  thematicid_identifier character varying(4000),
  thematicid_identifierscheme character(13),
  gn_language character(3),
  name_spelling_text character varying(4000),
  name_spelling_script character(4),
  geometry geometry(MultiPolygon,25832),
  zonetype character(80),
  specialisedzonetype character(17),
  designatperiod_begin_indeterm character(7),
  designationperiod_end timestamp(0) without time zone,
  environmentaldomain character(73),
  competentauth_individualname character(7),
  competentauth_organisationname character(42),
  competentauth_positionname character(7),
  competentauth_contact character(17),
  competentauth_role character(68),
  beginlifespanversion timestamp(6) with time zone,
  endlifespanversion character(17),
  plan1 character(17),
  legislationname character(101),
  legislationshortname character(23),
  dateenteredintoforce character(10),
  datetype character(11),
  link1 character(47),
  specificreference character(17),
  legislationlevel character(67)
)
```

I'm using Hale Studio 3.5.0 (64 bit) on Win 10, and importing from postgres  10.7 and postgis 2.5.

The issue might spill over into 'Export' -> 'Transformed data', which doesn't get any SRS information attached to the geometries.

Is this a bug or am I doing it wrong?

Regards,
Jonas

![image](https://user-images.githubusercontent.com/12182543/53240627-81639d80-369f-11e9-88b3-ce76a6c31680.png)

**Comment by florianesser** [comment]
That warning is generated [here](https://github.com/halestudio/hale/blob/479017ea2b7fea81c5314f03cf6442f9427a44cd/io/plugins/eu.esdihumboldt.hale.io.jdbc.postgresql/src/eu/esdihumboldt/hale/io/jdbc/postgresql/PostGISGeometries.java#L111). It looks like the `srid` returned by [this query](https://github.com/halestudio/hale/blob/479017ea2b7fea81c5314f03cf6442f9427a44cd/io/plugins/eu.esdihumboldt.hale.io.jdbc.postgresql/src/eu/esdihumboldt/hale/io/jdbc/postgresql/PostGISGeometries.java#L89) is `0`. At first glance this looks like an error in the geometries.

**Comment by thorsten-reitz** [comment]
@dollarklavs I recently ran into this issue as well, and it turned out that access privileges were not set correctly for the database user, which lead to the geometries being returned with a srid of 0. In this case, the customer set up the privileges correctly, then reinserted her data, and then it worked.

If this works for you, I'd close this ticket.
