### ISSUE TITLE
Make Integer and Float values comparable for Join

### ISSUE THREAD

**Issue by JohannaOtt** [halestudio/hale#737]
In a customer's project, a Join is needed that is based on an attribute with an Integer value in one of the feature types and on an attribute with a Float value in the other one.
The Float version of it holds the same values as the Integer one but ".0" is added.
In order to make the two attributes comparable, one idea was to cut the post-comma part of each Float used for a Join (as a Join using two Float values won't appear anyway) and convert it into Integer.
In this case, there should be an information somewhere that Float values can't be used as Join attributes in order to avoid wrong usage of the Join function.
Alternatively, "cutting" Float values to Integer values could be added as option.

The customer affected wants to use this functionality in an automated workflow so that it should also be deployed in a new hale-cli version.

**Comment by thorsten-reitz** [comment]
@florianesser isn't this done or at least ready to be challenged?

**Comment by florianesser** [comment]
@thorsten-reitz Yes, it's been merged and can be tested.

**Comment by florianesser** [comment]
@JohannaOtt Could you use this successfully in your customer project?

**Comment by JohannaOtt** [comment]
I found an email from June 19th in which the customer confirms, the Join worked with build 15. So I assume this issue can be closed.
