### ISSUE TITLE
Enable users to search transformation  projects using tags when loading them from hale connect

### ISSUE THREAD

**Issue by JohannaOtt** [halestudio/hale#751]
Once https://wetransform.atlassian.net/browse/ING-1704 is Done, a user should be able to use the tags set on hale connect to filter transformation projects that are opened from hale connect.

**Comment by JohannaOtt** [comment]
This feature has never been asked for ever since.
I would therefore vote for closing the issue.
@stempler @florianesser Any objections?

**Comment by thorsten-reitz** [comment]
@JohannaOtt fine for me to close this.

**Comment by JohannaOtt** [comment]
As there were no objections, I continue closing this issue.
