### ISSUE TITLE
Provide feedback/error message to user when property used for Merge cannot be found

### ISSUE THREAD

**Issue by JohannaOtt** [halestudio/hale#754]
When changing the source schema of a transformation (in this case only the namespace changed, but the types' and attributes' names stayed stable) and with this, changing a property that is used for a Merge, there is no obvious information to the user that the Merge cannot be executed anymore. (Technically, it still is executed but merges all objects of the type together as the merging property information is missing).
There is an information on it in the error log, but no error message or warning in the Instance transformation messages.
It would be helpful to
- either make sure, the property used for a merge is replaced when something changes for the source schema and the transformations are changed using the dialogue when opening it for the first time
- or add the error occurring in the error log to the errors or warnings given in the Instance transformation context.

**Comment by JohannaOtt** [comment]
This is a very special case that I never ran into again IIRC.
I would therefore vote for closing the issue.
@florianesser @stempler Any objections?

**Comment by thorsten-reitz** [comment]
@JohannaOtt would be OK for me to close it.
