### ISSUE TITLE
Removal of project variable is not persisted on save

### ISSUE THREAD

**Issue by florianesser** [halestudio/hale#757]
In a project that contains a project variable, the removal of a variable via the settings dialog is not persisted to the project file upon save.

**Comment by Claudia-WE** [comment]
when removing the project variable and in addition change status of e.g. of OccuredValues in source data the removal is persisted. When closing the project a "Save changes ?" window will appear which is not the case when only the variable has been removed

**Comment by Claudia-WE** [comment]
To make it more clear:
remove variable --> Apply and Close --> change not persisted
remove variable and change status of e.g. occuredvalues --> Apply and Close --> change persisted

**Comment by Flaminietta** [comment]
This is what I observe:

1. if I create two or more project variables (`test_variable.png`)
2. and I use them for alignments of the kind "Formatted string" (`variable_1.png` and `variable_2.png`)
3. then, they are present in the final project file (`Test2Vars.halex.alignment.xml`)
4. if then I delete the project variable _test_variable_1_ but don't delete the alignment itself, which uses it, I still find the variable in the project file (`TestVar1.halex.alignment.xml`)
5. if instead I delete the variable and delete the alignment (with right-click >> delete), then also in the project file the variable disappears (TestVar1PlusDeletion.halex.alignment.xml) and the change persists

My conclusion would be that this might not be considered as a bug but we can document it somewher
![test_variables](https://user-images.githubusercontent.com/26147427/144574210-26e85c03-f3de-4e5b-baa7-6be4b68c457b.png)
![variable_2](https://user-images.githubusercontent.com/26147427/144574222-312a9c3a-5e28-4370-8f64-e0affeaf5664.png)
![variable_1](https://user-images.githubusercontent.com/26147427/144574213-2cc0eba9-3195-4e83-868f-6678493bf89e.png)

e.

**Comment by Flaminietta** [comment]
This is what I observe:

1. if I create two or more project variables (`test_variable.png`);
2. and I use them for alignments of the kind "Formatted string" (`variable_1.png` and `variable_2.png`);
3. then, they are present in the final project file;
4. if then I delete the project variable _test_variable_1_ but don't delete the alignment itself, which uses it, I still find the variable in the project file; 
5. if instead I delete the variable and delete the alignment (with right-click >> delete), then also in the project file the variable disappears and the change persists.

My conclusion would be that this might not be considered a bug but we can simply document it somewhere.

![test_variables](https://user-images.githubusercontent.com/26147427/144574210-26e85c03-f3de-4e5b-baa7-6be4b68c457b.png)

![variable_2](https://user-images.githubusercontent.com/26147427/144574222-312a9c3a-5e28-4370-8f64-e0affeaf5664.png)

![variable_1](https://user-images.githubusercontent.com/26147427/144574213-2cc0eba9-3195-4e83-868f-6678493bf89e.png)
