### ISSUE TITLE
Gml:name attribute is not recognised for Xplanung schema - dataset containing gml:name cannot be read

### ISSUE THREAD

**Issue by JohannaOtt** [halestudio/hale#764]
When trying to load an XPlanung GML containing an object with
1. a gml:name attribute
2. all other attributes using the default namespace instead of an explicitely defined namespace
to hale studio using this transformation project https://test.haleconnect.de/#/transformation/org/25/8bc3330a-d8da-40be-aa5f-0be8bc1dd77b/overview, only the object itself and the gml:id are recognised. All other attributes are not loaded.

The reason for that is the occurrence of the gml:name attribute. There are two issues involved:
1. When looking at the source schema, no gml:name attribute is displayed, even though the gml:name attribute is not removed in the XPlanung GML profile: http://www.xplanungwiki.de/upload/XPlanGML/5.0/Schema/XPlanGML_5_0_Schemata.zip - the attribute should be displayed.
2. When trying to load the dataset with the default import settings, only BP_Plan:id is loaded - the existence of one (for hale unexpected) attribute should not keep it from loading the others.

Additional information.
* When using the 'Read types and properties where the namespace does not match the schema' functionality at data import, all properties are loaded as expected.
* When removing the gml:name attribute from the dataset, the data is loading as expected (also without using the functionality mentioned above.

An example dataset to reproduce the behavior is linked in WGS-455.

**Comment by florianesser** [comment]
@JohannaOtt The issue should be fixed and be tested with [this build](http://build-artifacts.wetransform.to.s3-eu-central-1.amazonaws.com/index.html?prefix=travisci/hale/38/).

**Comment by JohannaOtt** [comment]
LGTM
