### ISSUE TITLE
hale sometimes generates random namespace prefix

### ISSUE THREAD

**Issue by florianesser** [halestudio/hale#767]
A user reported in this [forum thread](https://discuss.wetransform.to/#/thread/9rt/Prefix-for-target-namespace) that for one of their source datasets hale generates a random namespace prefix of the form `zdef-<number>` in the transformed output, while in another dataset hale use the namespace prefix defined in the XSD.

**Comment by thorsten-reitz** [comment]
@florianesser I haven't seen this in a very long time, do you think this might be closed?
