### ISSUE TITLE
Too many top-level instances may be generated in headless mode

### ISSUE THREAD

**Issue by florianesser** [halestudio/hale#774]
In headless mode, if transformed instances are stored in the Orient database, `OInstance.isInserted()` is then not checked when writing these instances which can result in too many instances being written.

**Comment by florianesser** [comment]
[Build containing fix](http://build-artifacts.wetransform.to.s3-eu-central-1.amazonaws.com/index.html?prefix=travisci/hale/44/)

**Comment by thorsten-reitz** [comment]
@florianesser Is there a specific procedure I can use to challenge this?

**Comment by florianesser** [comment]
@thorsten-reitz: @Kate-Lyndegaard had a problem with one of the MST datasets on haleconnect.com. I'll try to find the relevant Slack thread and point you to it.
