### ISSUE TITLE
Update Eclipse version to avoid slow start with Eclipse 4.8 (Photon)

### ISSUE THREAD

**Issue by JohannaOtt** [halestudio/hale#783]
Since updating the Eclipse version used to Eclipse 4.8 (Photon), the application is starting rather slow (compared to before the update).
In order to avoid that slow start of the application, the Eclipse version should be updated.

**Comment by florianesser** [comment]
Might make sense to tackle this in conjunction with #711

**Comment by thorsten-reitz** [comment]
Eclipse has been updated to 2020-03 here: #822 

Evaluation has shown only minor speed-up of start-up time (15s vs 13s). Still have to test whether screen sharing interferes with start up times as it used to.

Since this is a duplicate, I will close this ticket.
