### ISSUE TITLE
Support setting a CRS for GeoPackage export

### ISSUE THREAD

**Issue by thorsten-reitz** [halestudio/hale#789]
During export to a GeoPackage file, it should be possible to set the CRS which to use, like with other formats.

Currently, issues occur when writing geometries (Failed to convert Geometry to target SRS: Undefined Geographic CRS), which leads me to think the writer fails to recognize the CRS from the WKT definition:

```
{CRS=ETRS_1989_LAEA} MULTILINESTRING ((4635465.500892333 2795414.5685831346, 4635444.240845007 2795427.400050073, 4635351.504876959 2795483.3387031243, 4635326.098028481 2795498.8933384805, 4635293.708985012 2795519.0034867446))
```

The GeoPackage is then written, but apparently without CRS info, since QGIS then asks during import according to which CRS to display the data.

**Comment by apfelnymous** [comment]
Hey, in which overall working state is the geopackage writer in 4.0 so far ?

**Comment by thorsten-reitz** [comment]
I've been working with it for a couple of months, though it does have some limitations (as described in this ticket, as well as in #795 and #788).

**Comment by thorsten-reitz** [comment]
Estimated effort: 8h

**Comment by thorsten-reitz** [comment]
Tested with various CRS (EPSG:3035, EPSG:4258, EPSG:25832); LGTM.
