### ISSUE TITLE
Automatically add INSPIRE-Codespace to gml:identifier for INSPIRE target schemas

### ISSUE THREAD

**Issue by JohannaOtt** [halestudio/hale#792]
Version 4.0.0.SNAPSHOT
Build 640814825

When using an INSPIRE schema as target schema and adding values to gml:identifier (according to wetransform best practice https://www.wetransform.to/news/2018/02/12/best-practices-for-inspire-ids/), the codespace of this gml:identifier will always be 'http://inspire.ec.europa.eu/ids'.
In order to avoid assigning it to any feature type used in the application schema, the value could also be added for all objects created during data export.
This should only be applied if the schema used for the export is an INSPIRE schema.

**Comment by florianesser** [comment]
I would favour implementing this as a Writer option similar to `Omit nilReason attributes for elements that not nil`.
