### ISSUE TITLE
Improve read performance form GeoPackage

### ISSUE THREAD

**Issue by thorsten-reitz** [halestudio/hale#795]
Read performance from GeoPackages should be relatively good. However, when reading data from at least some GeoPackages such as the GIP.AT data set (https://www.data.gv.at/katalog/dataset/3fefc838-791d-4dde-975b-a4131a54e7c5), performance seems to be low on my i7 quad core with 32GB RAM and fast SSDs. Loading 10k objects took 126 seconds, while loading the same 10k objects from shapefile takes 15 seconds.

CPU utilization during load is about 17%. RAM usage fluctuates between a few hundred MB and 2GB (at -xmx12g). There always seem to be significant wait times between batches of 100 objects. Disc utilization is around 1%.

![grafik](https://user-images.githubusercontent.com/3470356/74424940-2815f080-4e53-11ea-9b4c-05512110064b.png)

Would be good to see if this is an issue in the underlying library or in our code.

**Comment by thorsten-reitz** [comment]
@JohannaOtt I would assume my PC (see above) is probably as fast as what Simon would have set up... more than 30.5GiB of memory do not make much sense for a hale studio process anyway, and hale studio doesn't properly utilize many cores in many processes.

**Comment by thorsten-reitz** [comment]
@florianesser the read performance has indeed improved significantly with build https://builds.wetransform.to/job/hale/job/hale%7Epublish(master)/482/

I now get a load rate of 800 rows/second, about 10 times faster than before :). Will do a large test with 5+M rows next.

**Comment by florianesser** [comment]
@thorsten-reitz Do you think we can close this ticket or should we still look for further improvements?

**Comment by thorsten-reitz** [comment]
This ticket can be closed.
