### ISSUE TITLE
Add ISO metadata schema to presets

### ISSUE THREAD

**Issue by thorsten-reitz** [halestudio/hale#801]
We might consider inclusing this as an offline preset, since the schema locations haven't been stable.

**Comment by thorsten-reitz** [comment]
Estimated effort:
Offline preset: 6h to 8h 
URL preset: 1h

**Comment by florianesser** [comment]
I added is a preset for now ([commit](https://github.com/halestudio/hale/pull/838/commits/a46cefc8241578b6fe751d4745a267ec76dde155)). I'd suggest to include all of the 19139 schemas as resources in a future release.

**Comment by thorsten-reitz** [comment]
LGTM.
