### ISSUE TITLE
Offset added by mapping from date to date using rename

### ISSUE THREAD

**Issue by lgoltz** [halestudio/hale#805]
We created a mapping with 'Rename' from one date to another. Source and target schemas are XSD-Files. Source and Target properties are date types (xs:date). 
Using HALE Studio the target data does not contain the offset. But the transformed GML file contains an offset:

Source:
```
 <datum>2014-01-17</datum>
```
Target: 
```
   <datum>2014-01-17+01:00</datum>
```
Is it possible to avoid the offset if the transformation results in a GM file?

**Comment by stempler** [comment]
That's because the pre Java 8 date/time types are used internally. They don't model time zones explicitly so they implicitly assume a time zone (which is really annoying). See https://github.com/halestudio/hale/issues/316#issuecomment-290065658 for a workaround.

**Comment by stempler** [comment]
Assuming this is clarified. Feel free to reopen if there is an open question.
