### ISSUE TITLE
New resources section in hale studio documentation 

### ISSUE THREAD

**Issue by akshatbajaj10** [halestudio/hale#807]
The idea behind adding this would be to ensure that hale studio users (especially new users) can easily refer to a wide variety of sources. This section should be easily accessible in our documentation (maybe directly in the navigation tab?).

The resources are as follows: 
-       [Absolute beginners may start here](http://help.halestudio.org/latest/index.jsp?topic=%2Feu.esdihumboldt.hale.doc.user%2Fhtml%2Fgetting_started%2Fmain_workflow.html&cp=0_2_1)
-       [Search for free text in the online help]( http://help.halestudio.org/latest/index.jsp)
-       Review the FAQs (external link is not yet ready)
-       Watch the introductory webinar (link to be added later)
-       [Use the Support Forum](https://discuss.wetransform.to/#/forum)
-       Use the chat function on our website
-       Call us at +49 6151 6290890
-       [Arrange an individual training (remote or on-premise)](https://www.wetransform.to/services/workshops/)
-       [Get a professional support subscription ](https://www.wetransform.to/services/support/)(bearbeitet)

Additionally, "Point of Contact" in our hale studio documentation (http://help.halestudio.org/latest/topic/eu.esdihumboldt.hale.doc.user/html/pointofcontact.html?cp=0_8) refers to the phone number, "+49 6151 155 408". This is to be changed to "+49 6151 6290890".

**Comment by stempler** [comment]
The link to the tutorial video in "For a quick start there is a tutorial video online" is no longer valid as well.

**Comment by stempler** [comment]
Correct link to the point of contact information:
http://help.halestudio.org/latest/topic/eu.esdihumboldt.hale.doc.user/html/pointofcontact.html?cp=0_8

**Comment by stempler** [comment]
@thorsten-reitz Should we use the link from the website (https://www.youtube.com/playlist?list=PL-BcE8VJZCDj4ah3hdqPUfZH5ORaGzZVU) for the tutorial video(s) or is that also out-of-date?

**Comment by thorsten-reitz** [comment]
@stempler These are all pretty outdated. Maybe we can use the webinar recording planned for end of April as a better intro video.

**Comment by akshatbajaj10** [comment]
I have made changes to my initial comment and the structure of the issue based on discussion with Christopher and Thorsten.

**Comment by thorsten-reitz** [comment]
@JohannaOtt In case you take over the other issue on documentation, can you also deal with this one?

**Comment by JohannaOtt** [comment]
Is no covered in #816
