### ISSUE TITLE
Remove whitespace from pos when importing gml geometries

### ISSUE THREAD

**Issue by JohannaOtt** [halestudio/hale#808]
If source data contains geometries with pos elements structured in the following way (coordinates are provided in their own line)
![grafik](https://user-images.githubusercontent.com/34163838/79444597-a6ba1600-7fdb-11ea-80a2-0a3d67a0702a.png)
hale studio reads the geometry as a 3D geometry with the first value being null: 
![grafik](https://user-images.githubusercontent.com/34163838/79448907-8e012e80-7fe2-11ea-8f68-eea35acfa643.png)

When changing the structure in a way that the pos value is in the same line as its tags 
![grafik](https://user-images.githubusercontent.com/34163838/79458894-c90b5e00-7ff2-11ea-8808-383867399f33.png) it is correctly recognised: 
![grafik](https://user-images.githubusercontent.com/34163838/79459003-ec360d80-7ff2-11ea-8cd5-646e76853736.png)

There is test data available on that (test data for XPlanung 5.1 vollvektoriell FNP) in the relevant GitHub repository.

**Comment by thorsten-reitz** [comment]
LGTM, tested with build https://builds.wetransform.to/job/hale/job/hale~publish(master)/504/
