### ISSUE TITLE
Add a XPlanGML Writer

### ISSUE THREAD

**Issue by thorsten-reitz** [halestudio/hale#814]
Currently, it is possible to write XPlanGML by using the generic XML Writer with a Custom Root Element (XPlanAuszug). However, this requires more knowledge by the users and the general XML wirter also has fewer options than the GML writer.

We should thus add a dedicated XPlanGML writer based on the GML writer that supports the following features:

- Support at least XPlanGML 5.0, 5.1 and 5.2 (also, see #799)
- Write `XPlanAuszug` collections
- Allow partitioning by Plan (I would just use a simple checkbox setting); does not need to support objects shared by more than one plan
- Allow giving the partitioned files a name based on the element `xx_Plan.name` or on the `xx_Plan.gml:id`

**Comment by thorsten-reitz** [comment]
Effort estimate: 12h to 16h

**Comment by thorsten-reitz** [comment]
@florianesser I have tested the writer as is, LGTM. What I didn't find is the setting to use the plan's gml:id as the file name.

**Comment by florianesser** [comment]
@thorsten-reitz That and the split by plan feature are still under development. The first PR only included the writer.

**Comment by thorsten-reitz** [comment]
OK thanks. I supposed that I could just use the partitioning modes that were already present.

**Comment by thorsten-reitz** [comment]
LGTM, works as expected.
