### ISSUE TITLE
How to specify source CRS when importing from PostGIS

### ISSUE THREAD

**Issue by kl** [halestudio/hale#817]
Hello,
I have exported a shapefile to a PostGIS database (using shp2pgsql) and I can successfully import the PostGIS table into hale. The problem is the dialog where you specify the source CRS when adding the source data into hale does not appear, and when I try to export the transformed data I get an exception:

```Could not convert geometry to target CRS: No source CRS provided```

If I directly import the shapefile in hale I get the dialog to specify the source CRS. Any ideas on what I'm doing wrong?

**Comment by stempler** [comment]
The information is usually retrieved from the PostGIS table `geometry_columns` - when you add a geometry column an entry is usually created there automatically by PostGIS. A row there identifies table and column, as well as the `srid`. The `srid` is then looked up in the PostGIS table `spatial_ref_sys`.

So the respective entries need to be there and the database user needs to have access to both tables.

**Comment by kl** [comment]
The SRID was 0 in the database so I specified it with the -s flag in shp2pgsql and now it works. Thanks for the help!
