### ISSUE TITLE
Upgrade to GeoTools 21+

### ISSUE THREAD

**Issue by florianesser** [halestudio/hale#821]
reference: [GeoTools Java 11 Quickstart](https://docs.geotools.org/latest/userguide/tutorial/quickstart/java11.html)

Due to incompatbible changes in JTS dependency, requires also upgrade of:
- deegree to v3.4.12+ ([relevant commit](https://github.com/deegree/deegree3/commit/e4fb9bc44dba18fb118b54aa7007385f942e431e))

**Comment by thorsten-reitz** [comment]
Would this include https://github.com/halestudio/hale/issues/573 ?

**Comment by florianesser** [comment]
> Would this include #573 ?

Yes, I'd say that ticket would probably become obsolete after the upgrade.

**Comment by thorsten-reitz** [comment]
Loading projects with Groovy scripts that use old GeoTools dependencies works. I don't have a script that does a deep/direct call to a JTS class at hand though. Did anyone else test that?
