### ISSUE TITLE
Upgrade Eclipse platform to 2018-12 or later

### ISSUE THREAD

**Issue by florianesser** [halestudio/hale#822]
2018-12 is the first version with full Java 11 support ([source](https://www.eclipse.org/eclipse/news/4.10/jdt.php)).

**Comment by thorsten-reitz** [comment]
There are some extra arrows on the welcome page - maybe an artifact of this upgrade?
![grafik](https://user-images.githubusercontent.com/3470356/86024743-aacbd080-ba2d-11ea-817d-53ccc1268101.png)

**Comment by thorsten-reitz** [comment]
Startup time seems to have improved with the latest builds, maybe a result of removing the server parts?

**Comment by stempler** [comment]
> maybe a result of removing the server parts?

No server bundles were part of the desktop application. That was just about removing stuff that is not used anymore (the server product).

**Comment by thorsten-reitz** [comment]
Hm, OK. Just timed the difference, it isn't massive - the build from 20200619 is starting about 2s slower (15s) than the latest build (13s).
