### ISSUE TITLE
Remove unused hale server dependencies

### ISSUE THREAD

**Issue by thorsten-reitz** [halestudio/hale#823]
To ease migration to JDK 11, we decided to remove the old unused hale server code and related dependencies.

**Comment by thorsten-reitz** [comment]
@florianesser can I already challenge this? If yes, how?

**Comment by florianesser** [comment]
@thorsten-reitz The `server/` directory was removed from the sources in [this commit](https://github.com/halestudio/hale/commit/a80e4ffaca55d0f13fedd1db869d1cb4a65a40b1). I don't think you can challenge anything in the application as the server code was not included there anyway. @stempler Do you agree?
