### ISSUE TITLE
Make sure no duplicate field names are used when writing GeoPackage

### ISSUE THREAD

**Issue by thorsten-reitz** [halestudio/hale#834]
When using a GML schema to write to a GeoPackage, an error can occur due to attribute swith the same local name being present. This e.g. happens for the `name` attribute. The default behaviour sshould be to favour the attribute defined in the target namespace. We may later handle this via the Model Transformation rules (#815 ).

![grafik](https://user-images.githubusercontent.com/3470356/86032791-2fbbe780-ba38-11ea-9f2f-e416902b65a5.png)

**Comment by Kate-Lyndegaard** [comment]
@thorsten-reitz  Can you provide an example test case for this issue, including transfo and data?
