### ISSUE TITLE
hale studio 4.0.0 does not start on macOS

### ISSUE THREAD

**Issue by florianesser** [halestudio/hale#849]
Startup hangs at splash screen before showing version information. Reproduced on macOS 10.13.4, happens both for installed app and when running from Eclipse.

**Comment by opeeters** [comment]
On macOS 10.15.6 launching `hale studio.app` ends with this message:
```
“hale studio.app” is damaged and can’t be opened. You should move it to the Bin.
```
After removing attributes like this:
```
xattr -cr '/Applications/hale studio.app'
```
it hangs at the splash screen state as described above.

**Comment by frippe12573** [comment]
@florianesser, @opeeters, @JohannaOtt 
On macOs 11.5.1 launching hale studio.app (both version 3.5.0 and 4.0.0 downloaded from the website) ends with this message:

`Alert: Failed to create the Java Virtual Machine`

The installe Java version is:
`java -version 
java version "1.8.0_301"
Java(TM) SE Runtime Environment (build 1.8.0_301-b09)
Java HotSpot(TM) 64-Bit Server VM (build 25.301-b09, mixed mode)`

hints?

**Comment by kapil-agnihotri** [comment]
In Mac, application flow hangs when loading `WKTPreferencesCRSFactory` and initialising the HSQL database during application startup. After the discussion with @stempler, we concluded that these steps can be skipped during the initialisation phase (for Mac version of hale studio). Also, in the previous builds of Mac Hale Studio application, `jre` was referred to and not bundled within the application (this was also one of the reasons for the application not proceeding from the splash screen). Now the change will also be made to bundle jdk8 within the Mac application similar to what is already done for Linux and windows based environments.

**Comment by kapil-agnihotri** [comment]
Changes to start the hale studio on macOS w.r.t. the splash screen is merged to the master.  However, the user must execute the below command in the `terminal` to launch the software after the installation:
```
xattr -cr '/Applications/hale studio.app'
```
Explanation
Newer versions of macOS (Catalina and later) includes [Gatekeeper technology](https://support.apple.com/en-us/HT202491) that mandates any software to be notarized for security reasons. Therefore, in these versions, when the hale studio software is downloaded from the internet, macOS adds extended attribute `com.apple.quarantine` to it and prevents its launch by generating the error as 
```
"hale studio" is damaged and can't be opened. You should move it to the Bin.
```

So, to run the hale studio software in these versions, the `extended attribute` must be removed after the installation.

**Comment by JohannaOtt** [comment]
@opeeters @frippe12573  The latest build where the workaround @kapil-agnihotri  describes can be applied to is available [here](http://build-artifacts.wetransform.to/index.html?prefix=travisci/hale/224/)

@florianesser As there is a [follow up ticket](https://github.com/halestudio/hale/issues/908) to overcome the remaining issue, I would be in favor of closing this issue. Do you agree?

**Comment by florianesser** [comment]
> As there is a follow up ticket to overcome the remaining issue, I would be in favor of closing this issue. Do you agree?

@JohannaOtt :+1:

**Comment by frippe12573** [comment]
@JohannaOtt that worked for me.
Thanks.

**Comment by opeeters** [comment]
Worked for me too..
Thanks for solving this!

**Comment by Flaminietta** [comment]
**Hale studio 4.0.0 crashes when doing some mapping in mac OS BigSur, v. 11.5.2, with chip Apple M1**

**Solution**

- Download Liberica JDK x86 release for mac [https://download.bell-sw.com/java/11.0.10+9/bellsoft-jdk11.0.10+9-macos-amd64.zip]
- copy the entire content of the top-level directory into `hale studio > Contents > Eclipse > jre > Contents > Home`
