### ISSUE TITLE
Add all schema locations to GML exports containing top level objects from several schemas

### ISSUE THREAD

**Issue by JohannaOtt** [halestudio/hale#856]
When exporting data with hale studio that is containing top level objects from several schemas (e.g. the case for INSPIRE Soil if OM_Observation objects are created), the files do not validate in the INSPIRE Validator with error messages such as:
`XML document '[...]': 3:67: cvc-complex-type.2.4.a: Invalid content was found starting with element '{"http://www.opengis.net/om/2.0":OM_Observation}'. One of '{"http://www.opengis.net/gml/3.2":AbstractFeature}' is expected.`

In order to make the files pass the INSPIRE Validator, the schemaLocation for all namespaces that are used in top level objects should explicitely be added to the exported GML file.

Related discussions on the failing tests in the INSPIRE Validator can be found [here](https://github.com/INSPIRE-MIF/helpdesk-validator/issues/353) and [here](https://github.com/INSPIRE-MIF/helpdesk-validator/issues/223).

**Comment by apfelnymous** [comment]
Anyone knows for this particular case whats the solution ? 
Including the namespace of OM_Observation "http://www.opengis.net/om/2.0" didnt get me anywhere yet.

**Comment by JohannaOtt** [comment]
I was just about to write a reply - good news that you already found the issue 👍

**Comment by JohannaOtt** [comment]
@apfelnymous We are currently working on this. Would you be able to share the file you mentioned [here](https://github.com/INSPIRE-MIF/helpdesk-validator/issues/223#issuecomment-698355418) with us?

**Comment by JohannaOtt** [comment]
@apfelnymous Would you be able to share the relevant file with us?

**Comment by JohannaOtt** [comment]
@apfelnymous Is that this relevant? If yes, could you please provide us with the file?
If not, we would like to move on closing the issue.

**Comment by JohannaOtt** [comment]
@apfelnymous As there was no more feedback, I will close this issue now. Please feel free to open a new one if you run into it again incl. example files.
