### ISSUE TITLE
Loading schemas with geometries is significantly slower in hale studio 4.0.0

### ISSUE THREAD

**Issue by florianesser** [halestudio/hale#861]
When loading projects that use source or target schemas with geometries, loading takes significantly longer than in previous versions. The console is flooded with the message
```
SEVERE: Could not find class com.vividsolutions.jts.geom.Geometry since the preferred bundle org.locationtech.jts is not installed
```

**Comment by florianesser** [comment]
Can be tested with [build 168](http://build-artifacts.wetransform.to/?prefix=travisci/hale/168/) or later.

**Comment by thorsten-reitz** [comment]
LGTM, tested with build https://builds.wetransform.to/job/hale/job/hale%7Epublish(master)/546/

**Comment by thorsten-reitz** [comment]
@florianesser should I have tested with the TravisCI build?

**Comment by florianesser** [comment]
@thorsten-reitz I don't expect differences between the Travis and the Jenkins builds, so testing either is fine from my perspective. The reason we still have two builds is that I couldn't implement the artifact upload step (which runs after the software build is completed) successfully on Travis due to timeouts.
