### ISSUE TITLE
Update schema location of XPlanung schemas

### ISSUE THREAD

**Issue by JohannaOtt** [halestudio/hale#867]
According to information from the XLeitstelle, the XPlanung schemas will not stay available at http://www.xplanungwiki.de/upload/XPlanGML/. They are already (and will be) available at the GDI-DE Registry (http://repository.gdi-de.org/schemas/de.xleitstelle.xplanung/).
The schema location for the XPlanung presets used in hale studio should therefore be changed to the GDI-DE URL.

**Comment by JohannaOtt** [comment]
@florianesser Can this be closed?

**Comment by florianesser** [comment]
@JohannaOtt If someone challenged this successfully, then yes.

**Comment by JohannaOtt** [comment]
I can confirm the new URLs are used when importing the schema presets with the latest hale studio build: 
![grafik](https://user-images.githubusercontent.com/34163838/130244971-4c814e69-afe3-4118-a505-54c403877d8f.png)
