### ISSUE TITLE
File selection dialog hangs on macOS

### ISSUE THREAD

**Issue by florianesser** [halestudio/hale#871]
When trying to open the file selection dialog via the `Browse...` button (see screenshot), the application freezes on macOS 10.15.7. This applies to both hale studio 3.5.0 and the 4.0.0 preview release.

Thank you @sfrese for reporting this problem!

<img width="696" alt="Screenshot 2020-11-20 at 06 32 21" src="https://user-images.githubusercontent.com/1867607/99782578-a22d8100-2b19-11eb-8dfd-004f619c1027.png">

**Comment by Flaminietta** [comment]
I have tested it with **hale studio version 4.1.0** release, **revision ea4ef49d702431ba64071cf82933aa6c90541b39** and it works.  I have macOS Big Sur version 11.6. @florianesser

**Comment by florianesser** [comment]
Closing based on @Flaminietta 's report
