### ISSUE TITLE
Investigate missing function documentation updates

### ISSUE THREAD

**Issue by Kate-Lyndegaard** [halestudio/hale#873]
In the 2021-01-14 Documentation meeting, we discussed the fact that recently updated function documentation does not appear in hale studio release 4.1. Florian was able to view the updates in his local version, however it cannot be viewed in the latest 4.1 desktop release. 

The purpose of this ticket is to investigate why the documentation updates are not included. 

Merged PR which contains the missing function updates: https://github.com/halestudio/hale/pull/854

**Comment by JohannaOtt** [comment]
@florianesser Didn't you report that this was addressed some time ago?

**Comment by florianesser** [comment]
@JohannaOtt Indeed I think this should be fixed by https://github.com/halestudio/hale/commit/0c3549e01b250021a2f7dd8f740ef13980efea3d. Would be great if you could challenge it.

**Comment by JohannaOtt** [comment]
I can confirm that the sections added in the mentioned PR display in the current build.
