### ISSUE TITLE
Validation of XPlan writer erroneously throws warnings on missing objects

### ISSUE THREAD

**Issue by JohannaOtt** [halestudio/hale#890]
Version 4.1.0.SNAPSHOT
Build 763247191
Revision df620a7f13f58d8b80d5f5b3f488e3c3a3229e35

When transforming several objects to XPlan and exporting them with the Xplan writer using the functionality to create separate output files for every plan element, the writer throws many warnings all following the same pattern
![grafik](https://user-images.githubusercontent.com/34163838/112179455-001ec200-8bfb-11eb-899d-70fc803c7004.png)
The warning is about objects that are referenced, but are missing. This is not true for the data - the gml files are containing both objects that are referencing each other.
The warning occurs multiple times for each of the exported plans.

**Comment by Kate-Lyndegaard** [comment]
@JohannaOtt Do you have the example file(s) used in the issue description?

**Comment by JohannaOtt** [comment]
I can currently not re-produce the issue. Currently waiting for confirmation if it can be closed.

**Comment by JohannaOtt** [comment]
It is re-producible, checked the wrong logs.
@Kate-Lyndegaard I can provide you with the respective alignment and files.
