### ISSUE TITLE
Not able to install Hale Studio

### ISSUE THREAD

**Issue by laers** [halestudio/hale#892]
Hi,

I have:
macOS version 10.15.7
Java version: Java 8 (8u262-b10)

I am: 
trying to install Hale studio 3.5.0

Fails:
When I try to run Hale Studio a message with "An error has occurred. See the log file
/Applications/hale studio.app/Contents/Eclipse/configuration/1617260646278.log." is returned.

The log file:
!SESSION 2021-04-01 09:04:05.852 -----------------------------------------------
eclipse.buildId=unknown
java.version=13.0.1
java.vendor=Oracle Corporation
BootLoader constants: OS=macosx, ARCH=x86_64, WS=cocoa, NL=da_DK
Command-line arguments:  -os macosx -ws cocoa -arch x86_64 -clean

!ENTRY eu.esdihumboldt.hale.io.jdbc.postgresql 4 0 2021-04-01 09:04:13.673
!MESSAGE FrameworkEvent ERROR
!STACK 0
org.osgi.framework.BundleException: Exception in eu.esdihumboldt.hale.io.jdbc.postgresql.internal.Activator.start() of bundle eu.esdihumboldt.hale.io.jdbc.postgresql....

**Comment by JohannaOtt** [comment]
Hi @laers , there is [this issue](https://github.com/halestudio/hale/issues/849) on issues with starting on macOS. Maybe the workaround opeeters describes in his comment might help for you, too. He is using 10.15.6 though.
There is also a comment in the [3.5.0 release notes](https://github.com/halestudio/hale/releases/tag/3.5.0) on Java 8 JDK installation for macOS users - did you see that?

**Comment by laers** [comment]
Thanks @JohannaOtt for the hint. I manage to complete the installation (4.0.0 snapshot) but had still some difficulties in opening HALE. A simple workaround is to open HALE in Terminal 
$ open -a "Hale Studio"

**Comment by Ottootto2010** [comment]
Hi I am having the same issue as described, but unfortunately the workaround does not work for me.

**Comment by JohannaOtt** [comment]
@Ottootto2010 Which version of macOS are you using?
