### ISSUE TITLE
Add option to overwrite structural Retype mapping for single elements

### ISSUE THREAD

**Issue by JohannaOtt** [halestudio/hale#909]
Currently, when using a structural Retype mapping, there is no option to change single elements.
Sometimes, there are use cases, where you want to keep the biggest part of the source data, but only want to change a few elements.
In these cases it would be helpful to be able to "overwrite" the mapping resulting from the structural Retype with an explicite mapping on property level.
So there should be something like an internal prioritization between the additional mapping on attribute level (higher priority) and the property "mappings" (not explicitely created) from the structural Retype (lower priority).

**Comment by thorsten-reitz** [comment]
I agree with this, it would be quite powerful to have such a feature.

**Comment by thorsten-reitz** [comment]
I have actually tested this in the last weeks, and have only encountered one case where it doesn't work: When there is a type level groovy operation (Groovy Merge, Groovy Retype). In all other cases (check the end repo for examples) this worked nicely.

**Comment by thorsten-reitz** [comment]
Related way of solving this: https://github.com/halestudio/hale/issues/970

**Comment by JohannaOtt** [comment]
Closed with https://github.com/halestudio/hale/pull/981
