### ISSUE TITLE
Remove "choice" from path created by insert attribute helper

### ISSUE THREAD

**Issue by JohannaOtt** [halestudio/hale#910]
When using the insert attribute name functionality (e.g. when creating a condition context) and there is a choice in the path of it, the word "choice" is inserted in the condition context:
![grafik](https://user-images.githubusercontent.com/34163838/130247933-e43d08b1-3e83-4a3e-bc0f-61065345caf6.png)
![grafik](https://user-images.githubusercontent.com/34163838/130247991-4ae50e75-d160-489d-9d97-58852757933d.png)

The condition context only works if "choice" is removed.

The insert attribute helper should be changed in a way that "choice" is not part of the path if there is a choice in it.

**Comment by thorsten-reitz** [comment]
@Flaminietta this might be a mango for you.
