### ISSUE TITLE
Update groovy compiler to version 2.5 or newer

### ISSUE THREAD

**Issue by JohannaOtt** [halestudio/hale#911]
hale»studio currently uses version 2.4 of the Groovy compiler. The Groovy Eclipse plugin [does not support this compiler version anymore](https://github.com/groovy/groovy-eclipse/issues/1183) since its version 4.0.0+. The Groovy 2.4 compiler is therefore no longer available when using Eclipse 2020-09 or later.

To avoid having to stick with old versions of Eclipse and the Groovy Eclipse plugin, the compiler version used in hale»studio should be upgraded.

**Comment by florianesser** [comment]
@kapil-agnihotri Wasn't this done as part of the Java 17 support?

**Comment by kapil-agnihotri** [comment]
Yes, it was part of Java 17 support https://github.com/halestudio/hale/releases/tag/5.0.0.
