### ISSUE TITLE
Implement GeoJSON schema reader

### ISSUE THREAD

**Issue by Claudia-WE** [halestudio/hale#929]
Currently it is not possile to load GeoJSON source schema and source data into hale studio. 
Tested with Version 4.1.0.SNAPSHOT, Build 202105251027 incl Pro-Plugin.

When trying to import source schema from json-File the following error appears:
![grafik](https://user-images.githubusercontent.com/54665693/137155185-c63646bc-3368-4954-ab66-f1c47bfb72fd.png)

**Comment by Claudia-WE** [comment]
Please ask me for test data when analysing this issue.

**Comment by florianesser** [comment]
To support reading JSON Schema, a corresponding schema reader would need to be implemented. The error message you're seeing comes from the fact that hale»studio tries to interpret the JSON Schema file as a hale»studio schema definition (HSD) file instead, which fails.
