### ISSUE TITLE
Add option to Date Extraction function to use lenient or non-lenient date/time interpretation

### ISSUE THREAD

**Issue by JohannaOtt** [halestudio/hale#936]
Currently, when using the Date Extraction function in hale studio, dates are parsed using the [lenient mode](https://docs.oracle.com/javase/8/docs/api/java/util/Calendar.html#setLenient(boolean)). That leads to the fact that "non-existing" date values (for example Feb 30th) are interpreted as correct dates (Mar 2nd for the example).
It would be helpful if users could decide on their own if a date should be interpreted using the lenient mode or if the function should throw an exception for such date values.

**Comment by JohannaOtt** [comment]
@Flaminietta Could this be assigned to you?

**Comment by Flaminietta** [comment]
https://github.com/halestudio/hale/pull/949

**Comment by JohannaOtt** [comment]
@Flaminietta Isn't that done?
