### ISSUE TITLE
reload and update schemas - project save function is not working

### ISSUE THREAD

**Issue by Claudia-WE** [halestudio/hale#956]
Hale studio 4.1.0. 

When I run 'File/Reload and update schemas' there is offer to 'Save changes to current project?'.
But id doesn't save changes after hit 'Yes'.

see also https://discuss.wetransform.to/#/thread/3fel/Save-project-after-reload-and-update-schemas

**Comment by Kate-Lyndegaard** [comment]
This issue is still reproducible in the latest build.
