### ISSUE TITLE
Add XPlanung version 6.0 to schema presets

### ISSUE THREAD

**Issue by JohannaOtt** [halestudio/hale#966]
Currently, only older XPlanung versions are contained in the schema presets. The latest version 6.0 should be added as well.

**Comment by thorsten-reitz** [comment]
Also, version 5.4 does seem to be missing so far.

**Comment by florianesser** [comment]
@JohannaOtt Should be present in hale»studio 5.0. Please challenge and close this if you agree, thanks!
