### ISSUE TITLE
Add option to Retype function with structural name to exclude top-level properties from copying

### ISSUE THREAD

**Issue by thorsten-reitz** [halestudio/hale#970]
Currently, it is not possible to make a Retype with structural rename enabled, when one needs to also apply property level functions for  specific behaviour.

With this adaptation to the retype function, one additional parameter would be added to the Function parameters page that allows the user to select properties which should be excluded from the copying.

**Comment by JohannaOtt** [comment]
Closed with https://github.com/halestudio/hale/pull/981
