### ISSUE TITLE
Shapefile writer shortens field names automatically during export

### ISSUE THREAD

**Issue by Claudia-WE** [halestudio/hale#974]
See shape file fields defined (HaleStudio in Screenshot) and short version of field names (QGIS in screenshot)
![image](https://user-images.githubusercontent.com/54665693/176923710-e234d7d2-a2b9-4799-92ec-691a1b4f62bd.png)

**Comment by Claudia-WE** [comment]
Field names for shapefiles and dBASE tables can be no more than 10 characters in length. But the shortening starts already with fieldname of 8 characters length. E.g. correctie --> correcti

**Comment by dgreefhorst** [comment]
It just does not use the field names that are in the schema, e.g. receptorID becomes reID

**Comment by Kate-Lyndegaard** [comment]
Currently investigating this issue.

**Comment by Kate-Lyndegaard** [comment]
This issue is no longer reproducible in the latest build.
