### ISSUE TITLE
hsd export is missing <hsd:entry> element for property with same name as type

### ISSUE THREAD

**Issue by JohannaOtt** [halestudio/hale#987]
Version 4.2.0.SNAPSHOT

Build 202208171957
Revision e09ae31e86cb5aa6fb65241215f330b08e4f8905

When loading a schema with a type containing a property using the same name as the type itself, the hsd exported from it does only contain one hsd:entry element with that name.
That leads to the index for this index being used in both, the hsd:type element and the hsd:property element:

![grafik](https://user-images.githubusercontent.com/34163838/192208062-58846ffd-27fc-407c-b62c-03055acc12db.png)

When loading the schema again with hale studio, it assumes the type being used in itself:
![grafik](https://user-images.githubusercontent.com/34163838/192208450-325cad7d-3218-4136-b6ae-38f43cc6d054.png)

**Comment by Kate-Lyndegaard** [comment]
Potential cause of https://github.com/halestudio/hale/issues/985

**Comment by stempler** [comment]
The problem is that the schema that the schema reader for Shapefiles creates, in this case includes two types with the same local name and namespace, so there are two competing definitions for the same type, which is invalid and can't be represented.

**Comment by JohannaOtt** [comment]
Cannot be reproduced with Build 202404171400 - Revision 119043308d27129762b754e0fcb775b8d12fd690
![grafik](https://github.com/halestudio/hale/assets/34163838/21b229e4-bfc5-4810-943b-d2982264def7)
![grafik](https://github.com/halestudio/hale/assets/34163838/83c02fa3-567e-4d9f-a269-e5c5ea3ca371)
Therefore closing this issue.
