### ISSUE TITLE
Enhancement: Provide option to overwrite content in Geopackage Writer instead of appending content

### ISSUE THREAD

**Issue by thorsten-reitz** [halestudio/hale#988]
The default behaviour of the GeoPackage writer is to append all transformed data to data that might already exist in the file selected as the target. This is consistent to other database writers in hale studio. 

However, we've received custoemr feedback several times asking for an option which would first clean the database, or just overwrite the file. This option should be disabled by default.

**Comment by thorsten-reitz** [comment]
Wasn't this done?

**Comment by florianesser** [comment]
Yes, it was released as part of 5.0.1.
